In [1]:
import pandas as pd
import numpy as np
from random import randint
from sklearn.linear_model import LinearRegression

In [2]:
x = [49,41,40,25,21,21,19,19,18,18,16,15,15,15,15,14,14,13,13,13,13,12,12,11,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,8,8,8,8,8,8,8,8,8,8,8,8,8,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1] 
y = [68.77,51.25,52.08,38.36,44.54,57.13,51.4,41.42,31.22,34.76,54.01,38.79,47.59,49.1,27.66,41.03,36.73,48.65,28.12,46.62,35.57,32.98,35,26.07,23.77,39.73,40.57,31.65,31.21,36.32,20.45,21.93,26.02,27.34,23.49,46.94,30.5,33.8,24.23,21.4,27.94,32.24,40.57,25.07,19.42,22.39,18.42,46.96,23.72,26.41,26.97,36.76,40.32,35.02,29.47,30.2,31,38.11,38.18,36.31,21.03,30.86,36.07,28.66,29.08,37.28,15.28,24.17,22.31,30.17,25.53,19.85,35.37,44.6,17.23,13.47,26.33,35.02,32.09,24.81,19.33,28.77,24.26,31.98,25.73,24.86,16.28,34.51,15.23,39.72,40.8,26.06,35.76,34.76,16.13,44.04,18.03,19.65,32.62,35.59,39.43,14.18,35.24,40.13,41.82,35.45,36.07,43.67,24.61,20.9,21.9,18.79,27.61,27.21,26.61,29.77,20.59,27.53,13.82,33.2,25,33.1,36.65,18.63,14.87,22.2,36.81,25.53,24.62,26.25,18.21,28.08,19.42,29.79,32.8,35.99,28.32,27.79,35.88,29.06,36.28,14.1,36.63,37.49,26.9,18.58,38.48,24.48,18.95,33.55,14.24,29.04,32.51,25.63,22.22,19,32.73,15.16,13.9,27.2,32.01,29.27,33,13.74,20.42,27.32,18.23,35.35,28.48,9.08,24.62,20.12,35.26,19.92,31.02,16.49,12.16,30.7,31.22,34.65,13.13,27.51,33.2,31.57,14.1,33.42,17.44,10.12,24.42,9.82,23.39,30.93,15.03,21.67,31.09,33.29,22.61,26.89,23.48,8.38,27.81,32.35,23.84]

# Linear Regression package 사용할 경우

In [3]:
model = LinearRegression()

In [4]:
x_ = pd.DataFrame(x)
y_ = pd.DataFrame(y)

In [5]:
x_ = x_.values.reshape(-1,1)
y_ = y_.values.reshape(-1,1)

In [6]:
model.fit(x_,y_)

LinearRegression()

In [7]:
model.intercept_

array([22.94755241])

In [8]:
model.coef_

array([[0.90386595]])

# 알고리즘 만들기

In [83]:
X = pd.DataFrame(x)

In [84]:
X[1] = np.ones(len(x), dtype = int)

In [85]:
w = np.empty(X.shape[1])

In [86]:
w.fill(10)

In [87]:
W = pd.DataFrame(w)

In [88]:
learning_rate = 0.01

In [89]:
Y = pd.DataFrame(y)

In [90]:
test_num = 1000

In [91]:
for i in range(test_num):
    cost = (X.dot(W) - Y).T
    W = W - (cost.dot(X) * learning_rate/len(X)).T
    print("test_num : ", i)
    print("slope : ",W.iloc[0])
    print("y-intercept : ",W.iloc[1])

test_num :  0
slope :  0    3.038134
Name: 0, dtype: float64
y-intercept :  0    9.503948
Name: 1, dtype: float64
test_num :  1
slope :  0    2.120221
Name: 0, dtype: float64
y-intercept :  0    9.491614
Name: 1, dtype: float64
test_num :  2
slope :  0    1.995545
Name: 0, dtype: float64
y-intercept :  0    9.542526
Name: 1, dtype: float64
test_num :  3
slope :  0    1.974995
Name: 0, dtype: float64
y-intercept :  0    9.601504
Name: 1, dtype: float64
test_num :  4
slope :  0    1.968129
Name: 0, dtype: float64
y-intercept :  0    9.661304
Name: 1, dtype: float64
test_num :  5
slope :  0    1.963078
Name: 0, dtype: float64
y-intercept :  0    9.720979
Name: 1, dtype: float64
test_num :  6
slope :  0    1.958283
Name: 0, dtype: float64
y-intercept :  0    9.780404
Name: 1, dtype: float64
test_num :  7
slope :  0    1.953541
Name: 0, dtype: float64
y-intercept :  0    9.839565
Name: 1, dtype: float64
test_num :  8
slope :  0    1.948824
Name: 0, dtype: float64
y-intercept :  0    9.89846
Name: 1, dtype: float64
test_num :  9
slope :  0    1.944129
Name: 0, dtype: float64
y-intercept :  0    9.957091
Name: 1, dtype: float64
test_num :  10
slope :  0    1.939455
Name: 0, dtype: float64
y-intercept :  0    10.015459
Name: 1, dtype: float64
test_num :  11
slope :  0    1.934802
Name: 0, dtype: float64
y-intercept :  0    10.073564
Name: 1, dtype: float64
test_num :  12
slope :  0    1.93017
Name: 0, dtype: float64
y-intercept :  0    10.131408
Name: 1, dtype: float64
test_num :  13
slope :  0    1.925558
Name: 0, dtype: float64
y-intercept :  0    10.188992
Name: 1, dtype: float64
test_num :  14
slope :  0    1.920968
Name: 0, dtype: float64
y-intercept :  0    10.246317
Name: 1, dtype: float64
test_num :  15
slope :  0    1.916398
Name: 0, dtype: float64
y-intercept :  0    10.303385
Name: 1, dtype: float64
test_num :  16
slope :  0    1.911849
Name: 0, dtype: float64
y-intercept :  0    10.360196
Name: 1, dtype: float64
test_num :  17
slope :  0    1.90732
Name: 0, dtype: float64
y-intercept :  0    10.416752
Name: 1, dtype: float64
test_num :  18
slope :  0    1.902811
Name: 0, dtype: float64
y-intercept :  0    10.473054
Name: 1, dtype: float64
test_num :  19
slope :  0    1.898323
Name: 0, dtype: float64
y-intercept :  0    10.529104
Name: 1, dtype: float64
test_num :  20
slope :  0    1.893854
Name: 0, dtype: float64
y-intercept :  0    10.584901
Name: 1, dtype: float64
test_num :  21
slope :  0    1.889406
Name: 0, dtype: float64
y-intercept :  0    10.640447
Name: 1, dtype: float64
test_num :  22
slope :  0    1.884978
Name: 0, dtype: float64
y-intercept :  0    10.695744
Name: 1, dtype: float64
test_num :  23
slope :  0    1.88057
Name: 0, dtype: float64
y-intercept :  0    10.750793
Name: 1, dtype: float64
test_num :  24
slope :  0    1.876182
Name: 0, dtype: float64
y-intercept :  0    10.805594
Name: 1, dtype: float64
test_num :  25
slope :  0    1.871813
Name: 0, dtype: float64
y-intercept :  0    10.860149
Name: 1, dtype: float64
test_num :  26
slope :  0    1.867464
Name: 0, dtype: float64
y-intercept :  0    10.914459
Name: 1, dtype: float64
test_num :  27
slope :  0    1.863134
Name: 0, dtype: float64
y-intercept :  0    10.968524
Name: 1, dtype: float64
test_num :  28
slope :  0    1.858824
Name: 0, dtype: float64
y-intercept :  0    11.022347
Name: 1, dtype: float64
test_num :  29
slope :  0    1.854533
Name: 0, dtype: float64
y-intercept :  0    11.075928
Name: 1, dtype: float64
test_num :  30
slope :  0    1.850262
Name: 0, dtype: float64
y-intercept :  0    11.129269
Name: 1, dtype: float64
test_num :  31
slope :  0    1.84601
Name: 0, dtype: float64
y-intercept :  0    11.182369
Name: 1, dtype: float64
test_num :  32
slope :  0    1.841777
Name: 0, dtype: float64
y-intercept :  0    11.235231
Name: 1, dtype: float64
test_num :  33
slope :  0    1.837563
Name: 0, dtype: float64
y-intercept :  0    11.287856
Name: 1, dtype: float64
test_num :  34
slope :  0    1.833367
Name: 0, dtype: float64
y-intercept :  0    11.340244
Name: 1, dtype: float64
test_num :  35
slope :  0    1.829191
Name: 0, dtype: float64
y-intercept :  0    11.392397
Name: 1, dtype: float64
test_num :  36
slope :  0    1.825033
Name: 0, dtype: float64
y-intercept :  0    11.444315
Name: 1, dtype: float64
test_num :  37
slope :  0    1.820895
Name: 0, dtype: float64
y-intercept :  0    11.496
Name: 1, dtype: float64
test_num :  38
slope :  0    1.816774
Name: 0, dtype: float64
y-intercept :  0    11.547453
Name: 1, dtype: float64
test_num :  39
slope :  0    1.812672
Name: 0, dtype: float64
y-intercept :  0    11.598675
Name: 1, dtype: float64
test_num :  40
slope :  0    1.808589
Name: 0, dtype: float64
y-intercept :  0    11.649666
Name: 1, dtype: float64
test_num :  41
slope :  0    1.804524
Name: 0, dtype: float64
y-intercept :  0    11.700428
Name: 1, dtype: float64
test_num :  42
slope :  0    1.800477
Name: 0, dtype: float64
y-intercept :  0    11.750963
Name: 1, dtype: float64
test_num :  43
slope :  0    1.796449
Name: 0, dtype: float64
y-intercept :  0    11.80127
Name: 1, dtype: float64
test_num :  44
slope :  0    1.792438
Name: 0, dtype: float64
y-intercept :  0    11.851351
Name: 1, dtype: float64
test_num :  45
slope :  0    1.788446
Name: 0, dtype: float64
y-intercept :  0    11.901208
Name: 1, dtype: float64
test_num :  46
slope :  0    1.784471
Name: 0, dtype: float64
y-intercept :  0    11.95084
Name: 1, dtype: float64
test_num :  47
slope :  0    1.780515
Name: 0, dtype: float64
y-intercept :  0    12.000249
Name: 1, dtype: float64
test_num :  48
slope :  0    1.776576
Name: 0, dtype: float64
y-intercept :  0    12.049436
Name: 1, dtype: float64
test_num :  49
slope :  0    1.772655
Name: 0, dtype: float64
y-intercept :  0    12.098403
Name: 1, dtype: float64
test_num :  50
slope :  0    1.768751
Name: 0, dtype: float64
y-intercept :  0    12.147149
Name: 1, dtype: float64
test_num :  51
slope :  0    1.764865
Name: 0, dtype: float64
y-intercept :  0    12.195676
Name: 1, dtype: float64
test_num :  52
slope :  0    1.760997
Name: 0, dtype: float64
y-intercept :  0    12.243985
Name: 1, dtype: float64
test_num :  53
slope :  0    1.757145
Name: 0, dtype: float64
y-intercept :  0    12.292077
Name: 1, dtype: float64
test_num :  54
slope :  0    1.753312
Name: 0, dtype: float64
y-intercept :  0    12.339953
Name: 1, dtype: float64
test_num :  55
slope :  0    1.749495
Name: 0, dtype: float64
y-intercept :  0    12.387614
Name: 1, dtype: float64
test_num :  56
slope :  0    1.745696
Name: 0, dtype: float64
y-intercept :  0    12.435061
Name: 1, dtype: float64
test_num :  57
slope :  0    1.741913
Name: 0, dtype: float64
y-intercept :  0    12.482295
Name: 1, dtype: float64
test_num :  58
slope :  0    1.738148
Name: 0, dtype: float64
y-intercept :  0    12.529316
Name: 1, dtype: float64
test_num :  59
slope :  0    1.734399
Name: 0, dtype: float64
y-intercept :  0    12.576126
Name: 1, dtype: float64
test_num :  60
slope :  0    1.730667
Name: 0, dtype: float64
y-intercept :  0    12.622726
Name: 1, dtype: float64
test_num :  61
slope :  0    1.726953
Name: 0, dtype: float64
y-intercept :  0    12.669116
Name: 1, dtype: float64
test_num :  62
slope :  0    1.723254
Name: 0, dtype: float64
y-intercept :  0    12.715298
Name: 1, dtype: float64
test_num :  63
slope :  0    1.719573
Name: 0, dtype: float64
y-intercept :  0    12.761273
Name: 1, dtype: float64
test_num :  64
slope :  0    1.715908
Name: 0, dtype: float64
y-intercept :  0    12.80704
Name: 1, dtype: float64
test_num :  65
slope :  0    1.712259
Name: 0, dtype: float64
y-intercept :  0    12.852603
Name: 1, dtype: float64
test_num :  66
slope :  0    1.708627
Name: 0, dtype: float64
y-intercept :  0    12.89796
Name: 1, dtype: float64
test_num :  67
slope :  0    1.705011
Name: 0, dtype: float64
y-intercept :  0    12.943114
Name: 1, dtype: float64
test_num :  68
slope :  0    1.701412
Name: 0, dtype: float64
y-intercept :  0    12.988065
Name: 1, dtype: float64
test_num :  69
slope :  0    1.697828
Name: 0, dtype: float64
y-intercept :  0    13.032814
Name: 1, dtype: float64
test_num :  70
slope :  0    1.694261
Name: 0, dtype: float64
y-intercept :  0    13.077361
Name: 1, dtype: float64
test_num :  71
slope :  0    1.690709
Name: 0, dtype: float64
y-intercept :  0    13.121709
Name: 1, dtype: float64
test_num :  72
slope :  0    1.687174
Name: 0, dtype: float64
y-intercept :  0    13.165858
Name: 1, dtype: float64
test_num :  73
slope :  0    1.683655
Name: 0, dtype: float64
y-intercept :  0    13.209808
Name: 1, dtype: float64
test_num :  74
slope :  0    1.680151
Name: 0, dtype: float64
y-intercept :  0    13.25356
Name: 1, dtype: float64
test_num :  75
slope :  0    1.676663
Name: 0, dtype: float64
y-intercept :  0    13.297116
Name: 1, dtype: float64
test_num :  76
slope :  0    1.673191
Name: 0, dtype: float64
y-intercept :  0    13.340476
Name: 1, dtype: float64
test_num :  77
slope :  0    1.669734
Name: 0, dtype: float64
y-intercept :  0    13.383642
Name: 1, dtype: float64
test_num :  78
slope :  0    1.666293
Name: 0, dtype: float64
y-intercept :  0    13.426613
Name: 1, dtype: float64
test_num :  79
slope :  0    1.662867
Name: 0, dtype: float64
y-intercept :  0    13.469392
Name: 1, dtype: float64
test_num :  80
slope :  0    1.659457
Name: 0, dtype: float64
y-intercept :  0    13.511978
Name: 1, dtype: float64
test_num :  81
slope :  0    1.656062
Name: 0, dtype: float64
y-intercept :  0    13.554373
Name: 1, dtype: float64
test_num :  82
slope :  0    1.652682
Name: 0, dtype: float64
y-intercept :  0    13.596577
Name: 1, dtype: float64
test_num :  83
slope :  0    1.649318
Name: 0, dtype: float64
y-intercept :  0    13.638592
Name: 1, dtype: float64
test_num :  84
slope :  0    1.645969
Name: 0, dtype: float64
y-intercept :  0    13.680418
Name: 1, dtype: float64
test_num :  85
slope :  0    1.642634
Name: 0, dtype: float64
y-intercept :  0    13.722056
Name: 1, dtype: float64
test_num :  86
slope :  0    1.639315
Name: 0, dtype: float64
y-intercept :  0    13.763507
Name: 1, dtype: float64
test_num :  87
slope :  0    1.63601
Name: 0, dtype: float64
y-intercept :  0    13.804772
Name: 1, dtype: float64
test_num :  88
slope :  0    1.632721
Name: 0, dtype: float64
y-intercept :  0    13.845851
Name: 1, dtype: float64
test_num :  89
slope :  0    1.629446
Name: 0, dtype: float64
y-intercept :  0    13.886746
Name: 1, dtype: float64
test_num :  90
slope :  0    1.626186
Name: 0, dtype: float64
y-intercept :  0    13.927457
Name: 1, dtype: float64
test_num :  91
slope :  0    1.62294
Name: 0, dtype: float64
y-intercept :  0    13.967985
Name: 1, dtype: float64
test_num :  92
slope :  0    1.61971
Name: 0, dtype: float64
y-intercept :  0    14.008331
Name: 1, dtype: float64
test_num :  93
slope :  0    1.616493
Name: 0, dtype: float64
y-intercept :  0    14.048496
Name: 1, dtype: float64
test_num :  94
slope :  0    1.613291
Name: 0, dtype: float64
y-intercept :  0    14.08848
Name: 1, dtype: float64
test_num :  95
slope :  0    1.610104
Name: 0, dtype: float64
y-intercept :  0    14.128285
Name: 1, dtype: float64
test_num :  96
slope :  0    1.606931
Name: 0, dtype: float64
y-intercept :  0    14.167911
Name: 1, dtype: float64
test_num :  97
slope :  0    1.603772
Name: 0, dtype: float64
y-intercept :  0    14.207358
Name: 1, dtype: float64
test_num :  98
slope :  0    1.600627
Name: 0, dtype: float64
y-intercept :  0    14.246629
Name: 1, dtype: float64
test_num :  99
slope :  0    1.597496
Name: 0, dtype: float64
y-intercept :  0    14.285723
Name: 1, dtype: float64
test_num :  100
slope :  0    1.59438
Name: 0, dtype: float64
y-intercept :  0    14.324641
Name: 1, dtype: float64
test_num :  101
slope :  0    1.591277
Name: 0, dtype: float64
y-intercept :  0    14.363385
Name: 1, dtype: float64
test_num :  102
slope :  0    1.588189
Name: 0, dtype: float64
y-intercept :  0    14.401954
Name: 1, dtype: float64
test_num :  103
slope :  0    1.585114
Name: 0, dtype: float64
y-intercept :  0    14.44035
Name: 1, dtype: float64
test_num :  104
slope :  0    1.582053
Name: 0, dtype: float64
y-intercept :  0    14.478574
Name: 1, dtype: float64
test_num :  105
slope :  0    1.579006
Name: 0, dtype: float64
y-intercept :  0    14.516626
Name: 1, dtype: float64
test_num :  106
slope :  0    1.575972
Name: 0, dtype: float64
y-intercept :  0    14.554507
Name: 1, dtype: float64
test_num :  107
slope :  0    1.572953
Name: 0, dtype: float64
y-intercept :  0    14.592218
Name: 1, dtype: float64
test_num :  108
slope :  0    1.569946
Name: 0, dtype: float64
y-intercept :  0    14.629759
Name: 1, dtype: float64
test_num :  109
slope :  0    1.566954
Name: 0, dtype: float64
y-intercept :  0    14.667132
Name: 1, dtype: float64
test_num :  110
slope :  0    1.563974
Name: 0, dtype: float64
y-intercept :  0    14.704336
Name: 1, dtype: float64
test_num :  111
slope :  0    1.561008
Name: 0, dtype: float64
y-intercept :  0    14.741374
Name: 1, dtype: float64
test_num :  112
slope :  0    1.558056
Name: 0, dtype: float64
y-intercept :  0    14.778245
Name: 1, dtype: float64
test_num :  113
slope :  0    1.555116
Name: 0, dtype: float64
y-intercept :  0    14.81495
Name: 1, dtype: float64
test_num :  114
slope :  0    1.55219
Name: 0, dtype: float64
y-intercept :  0    14.851491
Name: 1, dtype: float64
test_num :  115
slope :  0    1.549277
Name: 0, dtype: float64
y-intercept :  0    14.887867
Name: 1, dtype: float64
test_num :  116
slope :  0    1.546377
Name: 0, dtype: float64
y-intercept :  0    14.92408
Name: 1, dtype: float64
test_num :  117
slope :  0    1.543491
Name: 0, dtype: float64
y-intercept :  0    14.96013
Name: 1, dtype: float64
test_num :  118
slope :  0    1.540617
Name: 0, dtype: float64
y-intercept :  0    14.996018
Name: 1, dtype: float64
test_num :  119
slope :  0    1.537756
Name: 0, dtype: float64
y-intercept :  0    15.031745
Name: 1, dtype: float64
test_num :  120
slope :  0    1.534908
Name: 0, dtype: float64
y-intercept :  0    15.067312
Name: 1, dtype: float64
test_num :  121
slope :  0    1.532072
Name: 0, dtype: float64
y-intercept :  0    15.102718
Name: 1, dtype: float64
test_num :  122
slope :  0    1.52925
Name: 0, dtype: float64
y-intercept :  0    15.137966
Name: 1, dtype: float64
test_num :  123
slope :  0    1.52644
Name: 0, dtype: float64
y-intercept :  0    15.173055
Name: 1, dtype: float64
test_num :  124
slope :  0    1.523642
Name: 0, dtype: float64
y-intercept :  0    15.207987
Name: 1, dtype: float64
test_num :  125
slope :  0    1.520858
Name: 0, dtype: float64
y-intercept :  0    15.242761
Name: 1, dtype: float64
test_num :  126

slope :  0    1.518086
Name: 0, dtype: float64
y-intercept :  0    15.27738
Name: 1, dtype: float64
test_num :  127
slope :  0    1.515326
Name: 0, dtype: float64
y-intercept :  0    15.311842
Name: 1, dtype: float64
test_num :  128
slope :  0    1.512578
Name: 0, dtype: float64
y-intercept :  0    15.34615
Name: 1, dtype: float64
test_num :  129
slope :  0    1.509843
Name: 0, dtype: float64
y-intercept :  0    15.380304
Name: 1, dtype: float64
test_num :  130
slope :  0    1.507121
Name: 0, dtype: float64
y-intercept :  0    15.414305
Name: 1, dtype: float64
test_num :  131
slope :  0    1.50441
Name: 0, dtype: float64
y-intercept :  0    15.448152
Name: 1, dtype: float64
test_num :  132
slope :  0    1.501712
Name: 0, dtype: float64
y-intercept :  0    15.481848
Name: 1, dtype: float64
test_num :  133
slope :  0    1.499026
Name: 0, dtype: float64
y-intercept :  0    15.515392
Name: 1, dtype: float64
test_num :  134
slope :  0    1.496352
Name: 0, dtype: float64
y-intercept :  0    15.548785
Name: 1, dtype: float64
test_num :  135
slope :  0    1.49369
Name: 0, dtype: float64
y-intercept :  0    15.582028
Name: 1, dtype: float64
test_num :  136
slope :  0    1.491039
Name: 0, dtype: float64
y-intercept :  0    15.615122
Name: 1, dtype: float64
test_num :  137
slope :  0    1.488401
Name: 0, dtype: float64
y-intercept :  0    15.648068
Name: 1, dtype: float64
test_num :  138
slope :  0    1.485775
Name: 0, dtype: float64
y-intercept :  0    15.680865
Name: 1, dtype: float64
test_num :  139
slope :  0    1.48316
Name: 0, dtype: float64
y-intercept :  0    15.713515
Name: 1, dtype: float64
test_num :  140
slope :  0    1.480557
Name: 0, dtype: float64
y-intercept :  0    15.746018
Name: 1, dtype: float64
test_num :  141
slope :  0    1.477966
Name: 0, dtype: float64
y-intercept :  0    15.778375
Name: 1, dtype: float64
test_num :  142
slope :  0    1.475387
Name: 0, dtype: float64
y-intercept :  0    15.810587
Name: 1, dtype: float64
test_num :  143
slope :  0    1.472819
Name: 0, dtype: float64
y-intercept :  0    15.842654
Name: 1, dtype: float64
test_num :  144
slope :  0    1.470263
Name: 0, dtype: float64
y-intercept :  0    15.874577
Name: 1, dtype: float64
test_num :  145
slope :  0    1.467718
Name: 0, dtype: float64
y-intercept :  0    15.906356
Name: 1, dtype: float64
test_num :  146
slope :  0    1.465184
Name: 0, dtype: float64
y-intercept :  0    15.937993
Name: 1, dtype: float64
test_num :  147
slope :  0    1.462662
Name: 0, dtype: float64
y-intercept :  0    15.969488
Name: 1, dtype: float64
test_num :  148
slope :  0    1.460152
Name: 0, dtype: float64
y-intercept :  0    16.000841
Name: 1, dtype: float64
test_num :  149
slope :  0    1.457652
Name: 0, dtype: float64
y-intercept :  0    16.032053
Name: 1, dtype: float64
test_num :  150
slope :  0    1.455164
Name: 0, dtype: float64
y-intercept :  0    16.063125
Name: 1, dtype: float64
test_num :  151
slope :  0    1.452687
Name: 0, dtype: float64
y-intercept :  0    16.094057
Name: 1, dtype: float64
test_num :  152
slope :  0    1.450221
Name: 0, dtype: float64
y-intercept :  0    16.124851
Name: 1, dtype: float64
test_num :  153
slope :  0    1.447766
Name: 0, dtype: float64
y-intercept :  0    16.155506
Name: 1, dtype: float64
test_num :  154
slope :  0    1.445322
Name: 0, dtype: float64
y-intercept :  0    16.186023
Name: 1, dtype: float64
test_num :  155
slope :  0    1.442889
Name: 0, dtype: float64
y-intercept :  0    16.216403
Name: 1, dtype: float64
test_num :  156
slope :  0    1.440468
Name: 0, dtype: float64
y-intercept :  0    16.246647
Name: 1, dtype: float64
test_num :  157
slope :  0    1.438057
Name: 0, dtype: float64
y-intercept :  0    16.276755
Name: 1, dtype: float64
test_num :  158
slope :  0    1.435656
Name: 0, dtype: float64
y-intercept :  0    16.306727
Name: 1, dtype: float64
test_num :  159
slope :  0    1.433267
Name: 0, dtype: float64
y-intercept :  0    16.336565
Name: 1, dtype: float64
test_num :  160
slope :  0    1.430888
Name: 0, dtype: float64
y-intercept :  0    16.366269
Name: 1, dtype: float64
test_num :  161
slope :  0    1.42852
Name: 0, dtype: float64
y-intercept :  0    16.395839
Name: 1, dtype: float64
test_num :  162
slope :  0    1.426163
Name: 0, dtype: float64
y-intercept :  0    16.425276
Name: 1, dtype: float64
test_num :  163
slope :  0    1.423816
Name: 0, dtype: float64
y-intercept :  0    16.454582
Name: 1, dtype: float64
test_num :  164
slope :  0    1.42148
Name: 0, dtype: float64
y-intercept :  0    16.483755
Name: 1, dtype: float64
test_num :  165
slope :  0    1.419155
Name: 0, dtype: float64
y-intercept :  0    16.512798
Name: 1, dtype: float64
test_num :  166
slope :  0    1.416839
Name: 0, dtype: float64
y-intercept :  0    16.54171
Name: 1, dtype: float64
test_num :  167
slope :  0    1.414534
Name: 0, dtype: float64
y-intercept :  0    16.570492
Name: 1, dtype: float64
test_num :  168
slope :  0    1.41224
Name: 0, dtype: float64
y-intercept :  0    16.599144
Name: 1, dtype: float64
test_num :  169
slope :  0    1.409956
Name: 0, dtype: float64
y-intercept :  0    16.627668
Name: 1, dtype: float64
test_num :  170
slope :  0    1.407682
Name: 0, dtype: float64
y-intercept :  0    16.656064
Name: 1, dtype: float64
test_num :  171
slope :  0    1.405418
Name: 0, dtype: float64
y-intercept :  0    16.684332
Name: 1, dtype: float64
test_num :  172
slope :  0    1.403165
Name: 0, dtype: float64
y-intercept :  0    16.712474
Name: 1, dtype: float64
test_num :  173
slope :  0    1.400921
Name: 0, dtype: float64
y-intercept :  0    16.740488
Name: 1, dtype: float64
test_num :  174
slope :  0    1.398688
Name: 0, dtype: float64
y-intercept :  0    16.768377
Name: 1, dtype: float64
test_num :  175
slope :  0    1.396465
Name: 0, dtype: float64
y-intercept :  0    16.796141
Name: 1, dtype: float64
test_num :  176
slope :  0    1.394251
Name: 0, dtype: float64
y-intercept :  0    16.82378
Name: 1, dtype: float64
test_num :  177
slope :  0    1.392048
Name: 0, dtype: float64
y-intercept :  0    16.851294
Name: 1, dtype: float64
test_num :  178
slope :  0    1.389855
Name: 0, dtype: float64
y-intercept :  0    16.878685
Name: 1, dtype: float64
test_num :  179
slope :  0    1.387671
Name: 0, dtype: float64
y-intercept :  0    16.905953
Name: 1, dtype: float64
test_num :  180
slope :  0    1.385497
Name: 0, dtype: float64
y-intercept :  0    16.933099
Name: 1, dtype: float64
test_num :  181
slope :  0    1.383333
Name: 0, dtype: float64
y-intercept :  0    16.960122
Name: 1, dtype: float64
test_num :  182
slope :  0    1.381179
Name: 0, dtype: float64
y-intercept :  0    16.987024
Name: 1, dtype: float64
test_num :  183
slope :  0    1.379034
Name: 0, dtype: float64
y-intercept :  0    17.013806
Name: 1, dtype: float64
test_num :  184
slope :  0    1.376899
Name: 0, dtype: float64
y-intercept :  0    17.040466
Name: 1, dtype: float64
test_num :  185
slope :  0    1.374774
Name: 0, dtype: float64
y-intercept :  0    17.067007
Name: 1, dtype: float64
test_num :  186
slope :  0    1.372658
Name: 0, dtype: float64
y-intercept :  0    17.093429
Name: 1, dtype: float64
test_num :  187
slope :  0    1.370552
Name: 0, dtype: float64
y-intercept :  0    17.119732
Name: 1, dtype: float64
test_num :  188
slope :  0    1.368455
Name: 0, dtype: float64
y-intercept :  0    17.145917
Name: 1, dtype: float64
test_num :  189
slope :  0    1.366368
Name: 0, dtype: float64
y-intercept :  0    17.171985
Name: 1, dtype: float64
test_num :  190
slope :  0    1.364289
Name: 0, dtype: float64
y-intercept :  0    17.197935
Name: 1, dtype: float64
test_num :  191
slope :  0    1.362221
Name: 0, dtype: float64
y-intercept :  0    17.223768
Name: 1, dtype: float64
test_num :  192
slope :  0    1.360161
Name: 0, dtype: float64
y-intercept :  0    17.249486
Name: 1, dtype: float64
test_num :  193
slope :  0    1.358111
Name: 0, dtype: float64
y-intercept :  0    17.275088
Name: 1, dtype: float64
test_num :  194
slope :  0    1.35607
Name: 0, dtype: float64
y-intercept :  0    17.300575
Name: 1, dtype: float64
test_num :  195
slope :  0    1.354038
Name: 0, dtype: float64
y-intercept :  0    17.325947
Name: 1, dtype: float64
test_num :  196
slope :  0    1.352016
Name: 0, dtype: float64
y-intercept :  0    17.351205
Name: 1, dtype: float64
test_num :  197
slope :  0    1.350002
Name: 0, dtype: float64
y-intercept :  0    17.37635
Name: 1, dtype: float64
test_num :  198
slope :  0    1.347998
Name: 0, dtype: float64
y-intercept :  0    17.401382
Name: 1, dtype: float64
test_num :  199
slope :  0    1.346002
Name: 0, dtype: float64
y-intercept :  0    17.426302
Name: 1, dtype: float64
test_num :  200
slope :  0    1.344015
Name: 0, dtype: float64
y-intercept :  0    17.451109
Name: 1, dtype: float64
test_num :  201
slope :  0    1.342038
Name: 0, dtype: float64
y-intercept :  0    17.475805
Name: 1, dtype: float64
test_num :  202
slope :  0    1.340069
Name: 0, dtype: float64
y-intercept :  0    17.50039
Name: 1, dtype: float64
test_num :  203
slope :  0    1.338109
Name: 0, dtype: float64
y-intercept :  0    17.524865
Name: 1, dtype: float64
test_num :  204
slope :  0    1.336158
Name: 0, dtype: float64
y-intercept :  0    17.549229
Name: 1, dtype: float64
test_num :  205
slope :  0    1.334216
Name: 0, dtype: float64
y-intercept :  0    17.573485
Name: 1, dtype: float64
test_num :  206
slope :  0    1.332282
Name: 0, dtype: float64
y-intercept :  0    17.597631
Name: 1, dtype: float64
test_num :  207
slope :  0    1.330357
Name: 0, dtype: float64
y-intercept :  0    17.621668
Name: 1, dtype: float64
test_num :  208
slope :  0    1.328441
Name: 0, dtype: float64
y-intercept :  0    17.645598
Name: 1, dtype: float64
test_num :  209
slope :  0    1.326533
Name: 0, dtype: float64
y-intercept :  0    17.66942
Name: 1, dtype: float64
test_num :  210
slope :  0    1.324634
Name: 0, dtype: float64
y-intercept :  0    17.693135
Name: 1, dtype: float64
test_num :  211
slope :  0    1.322744
Name: 0, dtype: float64
y-intercept :  0    17.716744
Name: 1, dtype: float64
test_num :  212
slope :  0    1.320862
Name: 0, dtype: float64
y-intercept :  0    17.740247
Name: 1, dtype: float64
test_num :  213
slope :  0    1.318988
Name: 0, dtype: float64
y-intercept :  0    17.763643
Name: 1, dtype: float64
test_num :  214
slope :  0    1.317123
Name: 0, dtype: float64
y-intercept :  0    17.786935
Name: 1, dtype: float64
test_num :  215
slope :  0    1.315266
Name: 0, dtype: float64
y-intercept :  0    17.810122
Name: 1, dtype: float64
test_num :  216
slope :  0    1.313418
Name: 0, dtype: float64
y-intercept :  0    17.833205
Name: 1, dtype: float64
test_num :  217
slope :  0    1.311577
Name: 0, dtype: float64
y-intercept :  0    17.856184
Name: 1, dtype: float64
test_num :  218
slope :  0    1.309746
Name: 0, dtype: float64
y-intercept :  0    17.87906
Name: 1, dtype: float64
test_num :  219
slope :  0    1.307922
Name: 0, dtype: float64
y-intercept :  0    17.901834
Name: 1, dtype: float64
test_num :  220
slope :  0    1.306106
Name: 0, dtype: float64
y-intercept :  0    17.924505
Name: 1, dtype: float64
test_num :  221
slope :  0    1.304299
Name: 0, dtype: float64
y-intercept :  0    17.947074
Name: 1, dtype: float64
test_num :  222
slope :  0    1.3025
Name: 0, dtype: float64
y-intercept :  0    17.969541
Name: 1, dtype: float64
test_num :  223
slope :  0    1.300709
Name: 0, dtype: float64
y-intercept :  0    17.991908
Name: 1, dtype: float64
test_num :  224
slope :  0    1.298926
Name: 0, dtype: float64
y-intercept :  0    18.014174
Name: 1, dtype: float64
test_num :  225
slope :  0    1.297151
Name: 0, dtype: float64
y-intercept :  0    18.03634
Name: 1, dtype: float64
test_num :  226
slope :  0    1.295384
Name: 0, dtype: float64
y-intercept :  0    18.058407
Name: 1, dtype: float64
test_num :  227
slope :  0    1.293625
Name: 0, dtype: float64
y-intercept :  0    18.080374
Name: 1, dtype: float64
test_num :  228
slope :  0    1.291873
Name: 0, dtype: float64
y-intercept :  0    18.102243
Name: 1, dtype: float64
test_num :  229
slope :  0    1.29013
Name: 0, dtype: float64
y-intercept :  0    18.124013
Name: 1, dtype: float64
test_num :  230
slope :  0    1.288395
Name: 0, dtype: float64
y-intercept :  0    18.145686
Name: 1, dtype: float64
test_num :  231
slope :  0    1.286667
Name: 0, dtype: float64
y-intercept :  0    18.167261
Name: 1, dtype: float64
test_num :  232
slope :  0    1.284947
Name: 0, dtype: float64
y-intercept :  0    18.188739
Name: 1, dtype: float64
test_num :  233
slope :  0    1.283235
Name: 0, dtype: float64
y-intercept :  0    18.210121
Name: 1, dtype: float64
test_num :  234
slope :  0    1.28153
Name: 0, dtype: float64
y-intercept :  0    18.231407
Name: 1, dtype: float64
test_num :  235
slope :  0    1.279833
Name: 0, dtype: float64
y-intercept :  0    18.252597
Name: 1, dtype: float64
test_num :  236
slope :  0    1.278144
Name: 0, dtype: float64
y-intercept :  0    18.273692
Name: 1, dtype: float64
test_num :  237
slope :  0    1.276462
Name: 0, dtype: float64
y-intercept :  0    18.294692
Name: 1, dtype: float64
test_num :  238
slope :  0    1.274788
Name: 0, dtype: float64
y-intercept :  0    18.315597
Name: 1, dtype: float64
test_num :  239
slope :  0    1.273122
Name: 0, dtype: float64
y-intercept :  0    18.336409
Name: 1, dtype: float64
test_num :  240
slope :  0    1.271462
Name: 0, dtype: float64
y-intercept :  0    18.357128
Name: 1, dtype: float64
test_num :  241
slope :  0    1.269811
Name: 0, dtype: float64
y-intercept :  0    18.377753
Name: 1, dtype: float64
test_num :  242
slope :  0    1.268167
Name: 0, dtype: float64
y-intercept :  0    18.398285
Name: 1, dtype: float64
test_num :  243
slope :  0    1.26653
Name: 0, dtype: float64
y-intercept :  0    18.418726
Name: 1, dtype: float64
test_num :  244
slope :  0    1.2649
Name: 0, dtype: float64
y-intercept :  0    18.439074
Name: 1, dtype: float64
test_num :  245
slope :  0    1.263278
Name: 0, dtype: float64
y-intercept :  0    18.459331
Name: 1, dtype: float64
test_num :  246
slope :  0    1.261663
Name: 0, dtype: float64
y-intercept :  0    18.479497
Name: 1, dtype: float64
test_num :  247
slope :  0    1.260056
Name: 0, dtype: float64
y-intercept :  0    18.499572
Name: 1, dtype: float64
test_num :  248
slope :  0    1.258455
Name: 0, dtype: float64
y-intercept :  0    18.519557
Name: 1, dtype: float64
test_num :  249
slope :  0    1.256862
Name: 0, dtype: float64
y-intercept :  0    18.539453
Name: 1, dtype: float64
test_num :  250
slope :  0    1.255276
Name: 0, dtype: float64
y-intercept :  0    18.559259
Name: 1, dtype: float64
test_num :  251
slope :  0    1.253697
Name: 0, dtype: float64
y-intercept :  0    18.578976
Name: 1, dtype: float64
test_num :  252
slope :  0    1.252125
Name: 0, dtype: float64
y-intercept :  0    18.598604
Name: 1, dtype: float64
test_num :  253
slope :  0    1.25056
Name: 0, dtype: float64
y-intercept :  0    18.618145
Name: 1, dtype: float64
test_num :  254
slope :  0    1.249003
Name: 0, dtype: float64
y-intercept :  0    18.637597
Name: 1, dtype: float64
test_num :  255
slope :  0    1.247452
Name: 0, dtype: float64
y-intercept :  0    18.656962
Name: 1, dtype: float64
test_num :  256
slope :  0    1.245908
Name: 0, dtype: float64
y-intercept :  0    18.67624
Name: 1, dtype: float64

test_num :  257
slope :  0    1.244371
Name: 0, dtype: float64
y-intercept :  0    18.695431
Name: 1, dtype: float64
test_num :  258
slope :  0    1.242842
Name: 0, dtype: float64
y-intercept :  0    18.714537
Name: 1, dtype: float64
test_num :  259
slope :  0    1.241318
Name: 0, dtype: float64
y-intercept :  0    18.733556
Name: 1, dtype: float64
test_num :  260
slope :  0    1.239802
Name: 0, dtype: float64
y-intercept :  0    18.75249
Name: 1, dtype: float64
test_num :  261
slope :  0    1.238293
Name: 0, dtype: float64
y-intercept :  0    18.771339
Name: 1, dtype: float64
test_num :  262
slope :  0    1.23679
Name: 0, dtype: float64
y-intercept :  0    18.790103
Name: 1, dtype: float64
test_num :  263
slope :  0    1.235294
Name: 0, dtype: float64
y-intercept :  0    18.808782
Name: 1, dtype: float64
test_num :  264
slope :  0    1.233805
Name: 0, dtype: float64
y-intercept :  0    18.827378
Name: 1, dtype: float64
test_num :  265
slope :  0    1.232323
Name: 0, dtype: float64
y-intercept :  0    18.845891
Name: 1, dtype: float64
test_num :  266
slope :  0    1.230847
Name: 0, dtype: float64
y-intercept :  0    18.86432
Name: 1, dtype: float64
test_num :  267
slope :  0    1.229378
Name: 0, dtype: float64
y-intercept :  0    18.882666
Name: 1, dtype: float64
test_num :  268
slope :  0    1.227915
Name: 0, dtype: float64
y-intercept :  0    18.90093
Name: 1, dtype: float64
test_num :  269
slope :  0    1.226459
Name: 0, dtype: float64
y-intercept :  0    18.919112
Name: 1, dtype: float64
test_num :  270
slope :  0    1.22501
Name: 0, dtype: float64
y-intercept :  0    18.937212
Name: 1, dtype: float64
test_num :  271
slope :  0    1.223567
Name: 0, dtype: float64
y-intercept :  0    18.955231
Name: 1, dtype: float64
test_num :  272
slope :  0    1.222131
Name: 0, dtype: float64
y-intercept :  0    18.973169
Name: 1, dtype: float64
test_num :  273
slope :  0    1.220701
Name: 0, dtype: float64
y-intercept :  0    18.991026
Name: 1, dtype: float64
test_num :  274
slope :  0    1.219277
Name: 0, dtype: float64
y-intercept :  0    19.008803
Name: 1, dtype: float64
test_num :  275
slope :  0    1.21786
Name: 0, dtype: float64
y-intercept :  0    19.0265
Name: 1, dtype: float64
test_num :  276
slope :  0    1.216449
Name: 0, dtype: float64
y-intercept :  0    19.044118
Name: 1, dtype: float64
test_num :  277
slope :  0    1.215045
Name: 0, dtype: float64
y-intercept :  0    19.061656
Name: 1, dtype: float64
test_num :  278
slope :  0    1.213646
Name: 0, dtype: float64
y-intercept :  0    19.079116
Name: 1, dtype: float64
test_num :  279
slope :  0    1.212255
Name: 0, dtype: float64
y-intercept :  0    19.096497
Name: 1, dtype: float64
test_num :  280
slope :  0    1.210869
Name: 0, dtype: float64
y-intercept :  0    19.1138
Name: 1, dtype: float64
test_num :  281
slope :  0    1.209489
Name: 0, dtype: float64
y-intercept :  0    19.131026
Name: 1, dtype: float64
test_num :  282
slope :  0    1.208116
Name: 0, dtype: float64
y-intercept :  0    19.148174
Name: 1, dtype: float64
test_num :  283
slope :  0    1.206749
Name: 0, dtype: float64
y-intercept :  0    19.165245
Name: 1, dtype: float64
test_num :  284
slope :  0    1.205388
Name: 0, dtype: float64
y-intercept :  0    19.182239
Name: 1, dtype: float64
test_num :  285
slope :  0    1.204034
Name: 0, dtype: float64
y-intercept :  0    19.199157
Name: 1, dtype: float64
test_num :  286
slope :  0    1.202685
Name: 0, dtype: float64
y-intercept :  0    19.215999
Name: 1, dtype: float64
test_num :  287
slope :  0    1.201342
Name: 0, dtype: float64
y-intercept :  0    19.232765
Name: 1, dtype: float64
test_num :  288
slope :  0    1.200006
Name: 0, dtype: float64
y-intercept :  0    19.249456
Name: 1, dtype: float64
test_num :  289
slope :  0    1.198675
Name: 0, dtype: float64
y-intercept :  0    19.266072
Name: 1, dtype: float64
test_num :  290
slope :  0    1.197351
Name: 0, dtype: float64
y-intercept :  0    19.282613
Name: 1, dtype: float64
test_num :  291
slope :  0    1.196032
Name: 0, dtype: float64
y-intercept :  0    19.29908
Name: 1, dtype: float64
test_num :  292
slope :  0    1.194719
Name: 0, dtype: float64
y-intercept :  0    19.315473
Name: 1, dtype: float64
test_num :  293
slope :  0    1.193412
Name: 0, dtype: float64
y-intercept :  0    19.331792
Name: 1, dtype: float64
test_num :  294
slope :  0    1.192111
Name: 0, dtype: float64
y-intercept :  0    19.348038
Name: 1, dtype: float64
test_num :  295
slope :  0    1.190816
Name: 0, dtype: float64
y-intercept :  0    19.364211
Name: 1, dtype: float64
test_num :  296
slope :  0    1.189527
Name: 0, dtype: float64
y-intercept :  0    19.380311
Name: 1, dtype: float64
test_num :  297
slope :  0    1.188243
Name: 0, dtype: float64
y-intercept :  0    19.396339
Name: 1, dtype: float64
test_num :  298
slope :  0    1.186966
Name: 0, dtype: float64
y-intercept :  0    19.412295
Name: 1, dtype: float64
test_num :  299
slope :  0    1.185694
Name: 0, dtype: float64
y-intercept :  0    19.428179
Name: 1, dtype: float64
test_num :  300
slope :  0    1.184427
Name: 0, dtype: float64
y-intercept :  0    19.443992
Name: 1, dtype: float64
test_num :  301
slope :  0    1.183167
Name: 0, dtype: float64
y-intercept :  0    19.459734
Name: 1, dtype: float64
test_num :  302
slope :  0    1.181912
Name: 0, dtype: float64
y-intercept :  0    19.475405
Name: 1, dtype: float64
test_num :  303
slope :  0    1.180663
Name: 0, dtype: float64
y-intercept :  0    19.491006
Name: 1, dtype: float64
test_num :  304
slope :  0    1.179419
Name: 0, dtype: float64
y-intercept :  0    19.506536
Name: 1, dtype: float64
test_num :  305
slope :  0    1.178181
Name: 0, dtype: float64
y-intercept :  0    19.521997
Name: 1, dtype: float64
test_num :  306
slope :  0    1.176948
Name: 0, dtype: float64
y-intercept :  0    19.537388
Name: 1, dtype: float64
test_num :  307
slope :  0    1.175721
Name: 0, dtype: float64
y-intercept :  0    19.552711
Name: 1, dtype: float64
test_num :  308
slope :  0    1.1745
Name: 0, dtype: float64
y-intercept :  0    19.567964
Name: 1, dtype: float64
test_num :  309
slope :  0    1.173284
Name: 0, dtype: float64
y-intercept :  0    19.583149
Name: 1, dtype: float64
test_num :  310
slope :  0    1.172073
Name: 0, dtype: float64
y-intercept :  0    19.598265
Name: 1, dtype: float64
test_num :  311
slope :  0    1.170868
Name: 0, dtype: float64
y-intercept :  0    19.613314
Name: 1, dtype: float64
test_num :  312
slope :  0    1.169669
Name: 0, dtype: float64
y-intercept :  0    19.628295
Name: 1, dtype: float64
test_num :  313
slope :  0    1.168474
Name: 0, dtype: float64
y-intercept :  0    19.643209
Name: 1, dtype: float64
test_num :  314
slope :  0    1.167285
Name: 0, dtype: float64
y-intercept :  0    19.658055
Name: 1, dtype: float64
test_num :  315
slope :  0    1.166102
Name: 0, dtype: float64
y-intercept :  0    19.672835
Name: 1, dtype: float64
test_num :  316
slope :  0    1.164924
Name: 0, dtype: float64
y-intercept :  0    19.687549
Name: 1, dtype: float64
test_num :  317
slope :  0    1.163751
Name: 0, dtype: float64
y-intercept :  0    19.702197
Name: 1, dtype: float64
test_num :  318
slope :  0    1.162583
Name: 0, dtype: float64
y-intercept :  0    19.716778
Name: 1, dtype: float64
test_num :  319
slope :  0    1.161421
Name: 0, dtype: float64
y-intercept :  0    19.731294
Name: 1, dtype: float64
test_num :  320
slope :  0    1.160263
Name: 0, dtype: float64
y-intercept :  0    19.745745
Name: 1, dtype: float64
test_num :  321
slope :  0    1.159111
Name: 0, dtype: float64
y-intercept :  0    19.760131
Name: 1, dtype: float64
test_num :  322
slope :  0    1.157965
Name: 0, dtype: float64
y-intercept :  0    19.774453
Name: 1, dtype: float64
test_num :  323
slope :  0    1.156823
Name: 0, dtype: float64
y-intercept :  0    19.78871
Name: 1, dtype: float64
test_num :  324
slope :  0    1.155686
Name: 0, dtype: float64
y-intercept :  0    19.802903
Name: 1, dtype: float64
test_num :  325
slope :  0    1.154555
Name: 0, dtype: float64
y-intercept :  0    19.817032
Name: 1, dtype: float64
test_num :  326
slope :  0    1.153428
Name: 0, dtype: float64
y-intercept :  0    19.831098
Name: 1, dtype: float64
test_num :  327
slope :  0    1.152307
Name: 0, dtype: float64
y-intercept :  0    19.8451
Name: 1, dtype: float64
test_num :  328
slope :  0    1.151191
Name: 0, dtype: float64
y-intercept :  0    19.85904
Name: 1, dtype: float64
test_num :  329
slope :  0    1.15008
Name: 0, dtype: float64
y-intercept :  0    19.872917
Name: 1, dtype: float64
test_num :  330
slope :  0    1.148973
Name: 0, dtype: float64
y-intercept :  0    19.886731
Name: 1, dtype: float64
test_num :  331
slope :  0    1.147872
Name: 0, dtype: float64
y-intercept :  0    19.900484
Name: 1, dtype: float64
test_num :  332
slope :  0    1.146776
Name: 0, dtype: float64
y-intercept :  0    19.914175
Name: 1, dtype: float64
test_num :  333
slope :  0    1.145684
Name: 0, dtype: float64
y-intercept :  0    19.927804
Name: 1, dtype: float64
test_num :  334
slope :  0    1.144598
Name: 0, dtype: float64
y-intercept :  0    19.941372
Name: 1, dtype: float64
test_num :  335
slope :  0    1.143516
Name: 0, dtype: float64
y-intercept :  0    19.954879
Name: 1, dtype: float64
test_num :  336
slope :  0    1.142439
Name: 0, dtype: float64
y-intercept :  0    19.968325
Name: 1, dtype: float64
test_num :  337
slope :  0    1.141367
Name: 0, dtype: float64
y-intercept :  0    19.981711
Name: 1, dtype: float64
test_num :  338
slope :  0    1.1403
Name: 0, dtype: float64
y-intercept :  0    19.995037
Name: 1, dtype: float64
test_num :  339
slope :  0    1.139238
Name: 0, dtype: float64
y-intercept :  0    20.008303
Name: 1, dtype: float64
test_num :  340
slope :  0    1.13818
Name: 0, dtype: float64
y-intercept :  0    20.021509
Name: 1, dtype: float64
test_num :  341
slope :  0    1.137128
Name: 0, dtype: float64
y-intercept :  0    20.034656
Name: 1, dtype: float64
test_num :  342
slope :  0    1.13608
Name: 0, dtype: float64
y-intercept :  0    20.047744
Name: 1, dtype: float64
test_num :  343
slope :  0    1.135036
Name: 0, dtype: float64
y-intercept :  0    20.060773
Name: 1, dtype: float64
test_num :  344
slope :  0    1.133998
Name: 0, dtype: float64
y-intercept :  0    20.073744
Name: 1, dtype: float64
test_num :  345
slope :  0    1.132964
Name: 0, dtype: float64
y-intercept :  0    20.086656
Name: 1, dtype: float64
test_num :  346
slope :  0    1.131934
Name: 0, dtype: float64
y-intercept :  0    20.09951
Name: 1, dtype: float64
test_num :  347
slope :  0    1.13091
Name: 0, dtype: float64
y-intercept :  0    20.112307
Name: 1, dtype: float64
test_num :  348
slope :  0    1.129889
Name: 0, dtype: float64
y-intercept :  0    20.125046
Name: 1, dtype: float64
test_num :  349
slope :  0    1.128874
Name: 0, dtype: float64
y-intercept :  0    20.137728
Name: 1, dtype: float64
test_num :  350
slope :  0    1.127863
Name: 0, dtype: float64
y-intercept :  0    20.150352
Name: 1, dtype: float64
test_num :  351
slope :  0    1.126856
Name: 0, dtype: float64
y-intercept :  0    20.162921
Name: 1, dtype: float64
test_num :  352
slope :  0    1.125855
Name: 0, dtype: float64
y-intercept :  0    20.175432
Name: 1, dtype: float64
test_num :  353
slope :  0    1.124857
Name: 0, dtype: float64
y-intercept :  0    20.187888
Name: 1, dtype: float64
test_num :  354
slope :  0    1.123864
Name: 0, dtype: float64
y-intercept :  0    20.200287
Name: 1, dtype: float64
test_num :  355
slope :  0    1.122876
Name: 0, dtype: float64
y-intercept :  0    20.212631
Name: 1, dtype: float64
test_num :  356
slope :  0    1.121892
Name: 0, dtype: float64
y-intercept :  0    20.224919
Name: 1, dtype: float64
test_num :  357
slope :  0    1.120912
Name: 0, dtype: float64
y-intercept :  0    20.237152
Name: 1, dtype: float64
test_num :  358
slope :  0    1.119937
Name: 0, dtype: float64
y-intercept :  0    20.24933
Name: 1, dtype: float64
test_num :  359
slope :  0    1.118966
Name: 0, dtype: float64
y-intercept :  0    20.261453
Name: 1, dtype: float64
test_num :  360
slope :  0    1.118
Name: 0, dtype: float64
y-intercept :  0    20.273522
Name: 1, dtype: float64
test_num :  361
slope :  0    1.117037
Name: 0, dtype: float64
y-intercept :  0    20.285537
Name: 1, dtype: float64
test_num :  362
slope :  0    1.11608
Name: 0, dtype: float64
y-intercept :  0    20.297498
Name: 1, dtype: float64
test_num :  363
slope :  0    1.115126
Name: 0, dtype: float64
y-intercept :  0    20.309405
Name: 1, dtype: float64
test_num :  364
slope :  0    1.114177
Name: 0, dtype: float64
y-intercept :  0    20.321258
Name: 1, dtype: float64
test_num :  365
slope :  0    1.113232
Name: 0, dtype: float64
y-intercept :  0    20.333058
Name: 1, dtype: float64
test_num :  366
slope :  0    1.112291
Name: 0, dtype: float64
y-intercept :  0    20.344805
Name: 1, dtype: float64
test_num :  367
slope :  0    1.111355
Name: 0, dtype: float64
y-intercept :  0    20.3565
Name: 1, dtype: float64
test_num :  368
slope :  0    1.110423
Name: 0, dtype: float64
y-intercept :  0    20.368142
Name: 1, dtype: float64
test_num :  369
slope :  0    1.109494
Name: 0, dtype: float64
y-intercept :  0    20.379731
Name: 1, dtype: float64
test_num :  370
slope :  0    1.108571
Name: 0, dtype: float64
y-intercept :  0    20.391269
Name: 1, dtype: float64
test_num :  371
slope :  0    1.107651
Name: 0, dtype: float64
y-intercept :  0    20.402754
Name: 1, dtype: float64
test_num :  372
slope :  0    1.106735
Name: 0, dtype: float64
y-intercept :  0    20.414188
Name: 1, dtype: float64
test_num :  373
slope :  0    1.105824
Name: 0, dtype: float64
y-intercept :  0    20.425571
Name: 1, dtype: float64
test_num :  374
slope :  0    1.104916
Name: 0, dtype: float64
y-intercept :  0    20.436902
Name: 1, dtype: float64
test_num :  375
slope :  0    1.104013
Name: 0, dtype: float64
y-intercept :  0    20.448183
Name: 1, dtype: float64
test_num :  376
slope :  0    1.103114
Name: 0, dtype: float64
y-intercept :  0    20.459413
Name: 1, dtype: float64
test_num :  377
slope :  0    1.102218
Name: 0, dtype: float64
y-intercept :  0    20.470592
Name: 1, dtype: float64
test_num :  378
slope :  0    1.101327
Name: 0, dtype: float64
y-intercept :  0    20.481721
Name: 1, dtype: float64
test_num :  379
slope :  0    1.10044
Name: 0, dtype: float64
y-intercept :  0    20.492801
Name: 1, dtype: float64
test_num :  380
slope :  0    1.099557
Name: 0, dtype: float64
y-intercept :  0    20.50383
Name: 1, dtype: float64
test_num :  381
slope :  0    1.098677
Name: 0, dtype: float64
y-intercept :  0    20.51481
Name: 1, dtype: float64
test_num :  382
slope :  0    1.097802
Name: 0, dtype: float64
y-intercept :  0    20.52574
Name: 1, dtype: float64
test_num :  383
slope :  0    1.096931
Name: 0, dtype: float64
y-intercept :  0    20.536622
Name: 1, dtype: float64
test_num :  384
slope :  0    1.096063
Name: 0, dtype: float64
y-intercept :  0    20.547454
Name: 1, dtype: float64
test_num :  385
slope :  0    1.0952
Name: 0, dtype: float64
y-intercept :  0    20.558238
Name: 1, dtype: float64
test_num :  386
slope :  0    1.09434
Name: 0, dtype: float64
y-intercept :  0    20.568974
Name: 1, dtype: float64
test_num :  387
slope :  0    1.093484
Name: 0, dtype: float64
y-intercept :  0    20.579661
Name: 1, dtype: float64
test_num :  388
slope :  0    1.092632
Name: 0, dtype: float64
y-intercept :  0    20.5903
Name: 1, dtype: float64
test_num :  389
slope :  0    1.091784
Name: 0, dtype: float64
y-intercept :  0    20.600891
Name: 1, dtype: float64
test_num :  390
slope :  0    1.09094
Name: 0, dtype: float64
y-intercept :  0    20.611435
Name: 1, dtype: float64
test_num :  391
slope :  0    1.090099
Name: 0, dtype: float64
y-intercept :  0    20.621931
Name: 1, dtype: float64
test_num :  392
slope :  0    1.089263
Name: 0, dtype: float64
y-intercept :  0    20.632381
Name: 1, dtype: float64
test_num :  393
slope :  0    1.08843
Name: 0, dtype: float64
y-intercept :  0    20.642783
Name: 1, dtype: float64
test_num :  394
slope :  0    1.0876
Name: 0, dtype: float64
y-intercept :  0    20.653139
Name: 1, dtype: float64
test_num :  395
slope :  0    1.086775
Name: 0, dtype: float64
y-intercept :  0    20.663448
Name: 1, dtype: float64
test_num :  396
slope :  0    1.085953
Name: 0, dtype: float64
y-intercept :  0    20.67371
Name: 1, dtype: float64
test_num :  397
slope :  0    1.085135
Name: 0, dtype: float64
y-intercept :  0    20.683927
Name: 1, dtype: float64
test_num :  398
slope :  0    1.08432
Name: 0, dtype: float64
y-intercept :  0    20.694097
Name: 1, dtype: float64
test_num :  399
slope :  0    1.08351
Name: 0, dtype: float64
y-intercept :  0    20.704222
Name: 1, dtype: float64
test_num :  400
slope :  0    1.082702
Name: 0, dtype: float64
y-intercept :  0    20.714302
Name: 1, dtype: float64
test_num :  401
slope :  0    1.081899
Name: 0, dtype: float64
y-intercept :  0    20.724336
Name: 1, dtype: float64
test_num :  402
slope :  0    1.081099
Name: 0, dtype: float64
y-intercept :  0    20.734325
Name: 1, dtype: float64
test_num :  403
slope :  0    1.080303
Name: 0, dtype: float64
y-intercept :  0    20.744269
Name: 1, dtype: float64
test_num :  404

slope :  0    1.07951
Name: 0, dtype: float64
y-intercept :  0    20.754169
Name: 1, dtype: float64
test_num :  405
slope :  0    1.078721
Name: 0, dtype: float64
y-intercept :  0    20.764024
Name: 1, dtype: float64
test_num :  406
slope :  0    1.077935
Name: 0, dtype: float64
y-intercept :  0    20.773835
Name: 1, dtype: float64
test_num :  407
slope :  0    1.077153
Name: 0, dtype: float64
y-intercept :  0    20.783602
Name: 1, dtype: float64
test_num :  408
slope :  0    1.076374
Name: 0, dtype: float64
y-intercept :  0    20.793324
Name: 1, dtype: float64
test_num :  409
slope :  0    1.075599
Name: 0, dtype: float64
y-intercept :  0    20.803004
Name: 1, dtype: float64
test_num :  410
slope :  0    1.074828
Name: 0, dtype: float64
y-intercept :  0    20.812639
Name: 1, dtype: float64
test_num :  411
slope :  0    1.074059
Name: 0, dtype: float64
y-intercept :  0    20.822232
Name: 1, dtype: float64
test_num :  412
slope :  0    1.073295
Name: 0, dtype: float64
y-intercept :  0    20.831781
Name: 1, dtype: float64
test_num :  413
slope :  0    1.072534
Name: 0, dtype: float64
y-intercept :  0    20.841287
Name: 1, dtype: float64
test_num :  414
slope :  0    1.071776
Name: 0, dtype: float64
y-intercept :  0    20.850751
Name: 1, dtype: float64
test_num :  415
slope :  0    1.071021
Name: 0, dtype: float64
y-intercept :  0    20.860172
Name: 1, dtype: float64
test_num :  416
slope :  0    1.07027
Name: 0, dtype: float64
y-intercept :  0    20.869551
Name: 1, dtype: float64
test_num :  417
slope :  0    1.069523
Name: 0, dtype: float64
y-intercept :  0    20.878887
Name: 1, dtype: float64
test_num :  418
slope :  0    1.068778
Name: 0, dtype: float64
y-intercept :  0    20.888182
Name: 1, dtype: float64
test_num :  419
slope :  0    1.068037
Name: 0, dtype: float64
y-intercept :  0    20.897435
Name: 1, dtype: float64
test_num :  420
slope :  0    1.0673
Name: 0, dtype: float64
y-intercept :  0    20.906646
Name: 1, dtype: float64
test_num :  421
slope :  0    1.066565
Name: 0, dtype: float64
y-intercept :  0    20.915816
Name: 1, dtype: float64
test_num :  422
slope :  0    1.065834
Name: 0, dtype: float64
y-intercept :  0    20.924945
Name: 1, dtype: float64
test_num :  423
slope :  0    1.065107
Name: 0, dtype: float64
y-intercept :  0    20.934033
Name: 1, dtype: float64
test_num :  424
slope :  0    1.064382
Name: 0, dtype: float64
y-intercept :  0    20.94308
Name: 1, dtype: float64
test_num :  425
slope :  0    1.063661
Name: 0, dtype: float64
y-intercept :  0    20.952086
Name: 1, dtype: float64
test_num :  426
slope :  0    1.062943
Name: 0, dtype: float64
y-intercept :  0    20.961052
Name: 1, dtype: float64
test_num :  427
slope :  0    1.062228
Name: 0, dtype: float64
y-intercept :  0    20.969977
Name: 1, dtype: float64
test_num :  428
slope :  0    1.061517
Name: 0, dtype: float64
y-intercept :  0    20.978863
Name: 1, dtype: float64
test_num :  429
slope :  0    1.060808
Name: 0, dtype: float64
y-intercept :  0    20.987708
Name: 1, dtype: float64
test_num :  430
slope :  0    1.060103
Name: 0, dtype: float64
y-intercept :  0    20.996514
Name: 1, dtype: float64
test_num :  431
slope :  0    1.059401
Name: 0, dtype: float64
y-intercept :  0    21.00528
Name: 1, dtype: float64
test_num :  432
slope :  0    1.058702
Name: 0, dtype: float64
y-intercept :  0    21.014007
Name: 1, dtype: float64
test_num :  433
slope :  0    1.058007
Name: 0, dtype: float64
y-intercept :  0    21.022695
Name: 1, dtype: float64
test_num :  434
slope :  0    1.057314
Name: 0, dtype: float64
y-intercept :  0    21.031343
Name: 1, dtype: float64
test_num :  435
slope :  0    1.056625
Name: 0, dtype: float64
y-intercept :  0    21.039953
Name: 1, dtype: float64
test_num :  436
slope :  0    1.055938
Name: 0, dtype: float64
y-intercept :  0    21.048524
Name: 1, dtype: float64
test_num :  437
slope :  0    1.055255
Name: 0, dtype: float64
y-intercept :  0    21.057057
Name: 1, dtype: float64
test_num :  438
slope :  0    1.054575
Name: 0, dtype: float64
y-intercept :  0    21.065551
Name: 1, dtype: float64
test_num :  439
slope :  0    1.053898
Name: 0, dtype: float64
y-intercept :  0    21.074007
Name: 1, dtype: float64
test_num :  440
slope :  0    1.053223
Name: 0, dtype: float64
y-intercept :  0    21.082425
Name: 1, dtype: float64
test_num :  441
slope :  0    1.052552
Name: 0, dtype: float64
y-intercept :  0    21.090805
Name: 1, dtype: float64
test_num :  442
slope :  0    1.051884
Name: 0, dtype: float64
y-intercept :  0    21.099147
Name: 1, dtype: float64
test_num :  443
slope :  0    1.051219
Name: 0, dtype: float64
y-intercept :  0    21.107452
Name: 1, dtype: float64
test_num :  444
slope :  0    1.050557
Name: 0, dtype: float64
y-intercept :  0    21.11572
Name: 1, dtype: float64
test_num :  445
slope :  0    1.049898
Name: 0, dtype: float64
y-intercept :  0    21.123951
Name: 1, dtype: float64
test_num :  446
slope :  0    1.049242
Name: 0, dtype: float64
y-intercept :  0    21.132144
Name: 1, dtype: float64
test_num :  447
slope :  0    1.048589
Name: 0, dtype: float64
y-intercept :  0    21.140301
Name: 1, dtype: float64
test_num :  448
slope :  0    1.047939
Name: 0, dtype: float64
y-intercept :  0    21.148421
Name: 1, dtype: float64
test_num :  449
slope :  0    1.047291
Name: 0, dtype: float64
y-intercept :  0    21.156505
Name: 1, dtype: float64
test_num :  450
slope :  0    1.046647
Name: 0, dtype: float64
y-intercept :  0    21.164552
Name: 1, dtype: float64
test_num :  451
slope :  0    1.046005
Name: 0, dtype: float64
y-intercept :  0    21.172564
Name: 1, dtype: float64
test_num :  452
slope :  0    1.045367
Name: 0, dtype: float64
y-intercept :  0    21.180539
Name: 1, dtype: float64
test_num :  453
slope :  0    1.044731
Name: 0, dtype: float64
y-intercept :  0    21.188478
Name: 1, dtype: float64
test_num :  454
slope :  0    1.044098
Name: 0, dtype: float64
y-intercept :  0    21.196382
Name: 1, dtype: float64
test_num :  455
slope :  0    1.043468
Name: 0, dtype: float64
y-intercept :  0    21.20425
Name: 1, dtype: float64
test_num :  456
slope :  0    1.042841
Name: 0, dtype: float64
y-intercept :  0    21.212083
Name: 1, dtype: float64
test_num :  457
slope :  0    1.042216
Name: 0, dtype: float64
y-intercept :  0    21.21988
Name: 1, dtype: float64
test_num :  458
slope :  0    1.041595
Name: 0, dtype: float64
y-intercept :  0    21.227643
Name: 1, dtype: float64
test_num :  459
slope :  0    1.040976
Name: 0, dtype: float64
y-intercept :  0    21.235371
Name: 1, dtype: float64
test_num :  460
slope :  0    1.04036
Name: 0, dtype: float64
y-intercept :  0    21.243064
Name: 1, dtype: float64
test_num :  461
slope :  0    1.039746
Name: 0, dtype: float64
y-intercept :  0    21.250722
Name: 1, dtype: float64
test_num :  462
slope :  0    1.039136
Name: 0, dtype: float64
y-intercept :  0    21.258346
Name: 1, dtype: float64
test_num :  463
slope :  0    1.038528
Name: 0, dtype: float64
y-intercept :  0    21.265936
Name: 1, dtype: float64
test_num :  464
slope :  0    1.037923
Name: 0, dtype: float64
y-intercept :  0    21.273492
Name: 1, dtype: float64
test_num :  465
slope :  0    1.037321
Name: 0, dtype: float64
y-intercept :  0    21.281013
Name: 1, dtype: float64
test_num :  466
slope :  0    1.036721
Name: 0, dtype: float64
y-intercept :  0    21.288501
Name: 1, dtype: float64
test_num :  467
slope :  0    1.036124
Name: 0, dtype: float64
y-intercept :  0    21.295955
Name: 1, dtype: float64
test_num :  468
slope :  0    1.03553
Name: 0, dtype: float64
y-intercept :  0    21.303376
Name: 1, dtype: float64
test_num :  469
slope :  0    1.034938
Name: 0, dtype: float64
y-intercept :  0    21.310764
Name: 1, dtype: float64
test_num :  470
slope :  0    1.034349
Name: 0, dtype: float64
y-intercept :  0    21.318118
Name: 1, dtype: float64
test_num :  471
slope :  0    1.033763
Name: 0, dtype: float64
y-intercept :  0    21.325439
Name: 1, dtype: float64
test_num :  472
slope :  0    1.033179
Name: 0, dtype: float64
y-intercept :  0    21.332727
Name: 1, dtype: float64
test_num :  473
slope :  0    1.032598
Name: 0, dtype: float64
y-intercept :  0    21.339983
Name: 1, dtype: float64
test_num :  474
slope :  0    1.03202
Name: 0, dtype: float64
y-intercept :  0    21.347206
Name: 1, dtype: float64
test_num :  475
slope :  0    1.031444
Name: 0, dtype: float64
y-intercept :  0    21.354396
Name: 1, dtype: float64
test_num :  476
slope :  0    1.030871
Name: 0, dtype: float64
y-intercept :  0    21.361555
Name: 1, dtype: float64
test_num :  477
slope :  0    1.0303
Name: 0, dtype: float64
y-intercept :  0    21.368681
Name: 1, dtype: float64
test_num :  478
slope :  0    1.029732
Name: 0, dtype: float64
y-intercept :  0    21.375775
Name: 1, dtype: float64
test_num :  479
slope :  0    1.029167
Name: 0, dtype: float64
y-intercept :  0    21.382837
Name: 1, dtype: float64
test_num :  480
slope :  0    1.028604
Name: 0, dtype: float64
y-intercept :  0    21.389867
Name: 1, dtype: float64
test_num :  481
slope :  0    1.028043
Name: 0, dtype: float64
y-intercept :  0    21.396866
Name: 1, dtype: float64
test_num :  482
slope :  0    1.027485
Name: 0, dtype: float64
y-intercept :  0    21.403833
Name: 1, dtype: float64
test_num :  483
slope :  0    1.02693
Name: 0, dtype: float64
y-intercept :  0    21.410769
Name: 1, dtype: float64
test_num :  484
slope :  0    1.026377
Name: 0, dtype: float64
y-intercept :  0    21.417674
Name: 1, dtype: float64
test_num :  485
slope :  0    1.025827
Name: 0, dtype: float64
y-intercept :  0    21.424548
Name: 1, dtype: float64
test_num :  486
slope :  0    1.025279
Name: 0, dtype: float64
y-intercept :  0    21.431391
Name: 1, dtype: float64
test_num :  487
slope :  0    1.024733
Name: 0, dtype: float64
y-intercept :  0    21.438203
Name: 1, dtype: float64
test_num :  488
slope :  0    1.02419
Name: 0, dtype: float64
y-intercept :  0    21.444985
Name: 1, dtype: float64
test_num :  489
slope :  0    1.023649
Name: 0, dtype: float64
y-intercept :  0    21.451736
Name: 1, dtype: float64
test_num :  490
slope :  0    1.023111
Name: 0, dtype: float64
y-intercept :  0    21.458457
Name: 1, dtype: float64
test_num :  491
slope :  0    1.022575
Name: 0, dtype: float64
y-intercept :  0    21.465148
Name: 1, dtype: float64
test_num :  492
slope :  0    1.022042
Name: 0, dtype: float64
y-intercept :  0    21.471808
Name: 1, dtype: float64
test_num :  493
slope :  0    1.021511
Name: 0, dtype: float64
y-intercept :  0    21.478439
Name: 1, dtype: float64
test_num :  494
slope :  0    1.020982
Name: 0, dtype: float64
y-intercept :  0    21.48504
Name: 1, dtype: float64
test_num :  495
slope :  0    1.020456
Name: 0, dtype: float64
y-intercept :  0    21.491611
Name: 1, dtype: float64
test_num :  496
slope :  0    1.019932
Name: 0, dtype: float64
y-intercept :  0    21.498153
Name: 1, dtype: float64
test_num :  497
slope :  0    1.019411
Name: 0, dtype: float64
y-intercept :  0    21.504665
Name: 1, dtype: float64
test_num :  498
slope :  0    1.018892
Name: 0, dtype: float64
y-intercept :  0    21.511148
Name: 1, dtype: float64
test_num :  499
slope :  0    1.018375
Name: 0, dtype: float64
y-intercept :  0    21.517602
Name: 1, dtype: float64
test_num :  500
slope :  0    1.01786
Name: 0, dtype: float64
y-intercept :  0    21.524027
Name: 1, dtype: float64
test_num :  501
slope :  0    1.017348
Name: 0, dtype: float64
y-intercept :  0    21.530423
Name: 1, dtype: float64
test_num :  502
slope :  0    1.016838
Name: 0, dtype: float64
y-intercept :  0    21.53679
Name: 1, dtype: float64
test_num :  503
slope :  0    1.016331
Name: 0, dtype: float64
y-intercept :  0    21.543129
Name: 1, dtype: float64
test_num :  504
slope :  0    1.015825
Name: 0, dtype: float64
y-intercept :  0    21.549439
Name: 1, dtype: float64
test_num :  505
slope :  0    1.015322
Name: 0, dtype: float64
y-intercept :  0    21.555721
Name: 1, dtype: float64
test_num :  506
slope :  0    1.014822
Name: 0, dtype: float64
y-intercept :  0    21.561975
Name: 1, dtype: float64
test_num :  507
slope :  0    1.014323
Name: 0, dtype: float64
y-intercept :  0    21.5682
Name: 1, dtype: float64
test_num :  508
slope :  0    1.013827
Name: 0, dtype: float64
y-intercept :  0    21.574398
Name: 1, dtype: float64
test_num :  509
slope :  0    1.013333
Name: 0, dtype: float64
y-intercept :  0    21.580567
Name: 1, dtype: float64
test_num :  510
slope :  0    1.012841
Name: 0, dtype: float64
y-intercept :  0    21.586709
Name: 1, dtype: float64
test_num :  511
slope :  0    1.012351
Name: 0, dtype: float64
y-intercept :  0    21.592824
Name: 1, dtype: float64
test_num :  512
slope :  0    1.011864
Name: 0, dtype: float64
y-intercept :  0    21.598911
Name: 1, dtype: float64
test_num :  513
slope :  0    1.011379
Name: 0, dtype: float64
y-intercept :  0    21.60497
Name: 1, dtype: float64
test_num :  514
slope :  0    1.010895
Name: 0, dtype: float64
y-intercept :  0    21.611003
Name: 1, dtype: float64
test_num :  515
slope :  0    1.010415
Name: 0, dtype: float64
y-intercept :  0    21.617008
Name: 1, dtype: float64
test_num :  516
slope :  0    1.009936
Name: 0, dtype: float64
y-intercept :  0    21.622986
Name: 1, dtype: float64
test_num :  517
slope :  0    1.009459
Name: 0, dtype: float64
y-intercept :  0    21.628937
Name: 1, dtype: float64
test_num :  518
slope :  0    1.008985
Name: 0, dtype: float64
y-intercept :  0    21.634862
Name: 1, dtype: float64
test_num :  519
slope :  0    1.008513
Name: 0, dtype: float64
y-intercept :  0    21.64076
Name: 1, dtype: float64
test_num :  520
slope :  0    1.008042
Name: 0, dtype: float64
y-intercept :  0    21.646632
Name: 1, dtype: float64
test_num :  521
slope :  0    1.007574
Name: 0, dtype: float64
y-intercept :  0    21.652477
Name: 1, dtype: float64
test_num :  522
slope :  0    1.007108
Name: 0, dtype: float64
y-intercept :  0    21.658296
Name: 1, dtype: float64
test_num :  523
slope :  0    1.006644
Name: 0, dtype: float64
y-intercept :  0    21.664088
Name: 1, dtype: float64
test_num :  524
slope :  0    1.006183
Name: 0, dtype: float64
y-intercept :  0    21.669855
Name: 1, dtype: float64
test_num :  525
slope :  0    1.005723
Name: 0, dtype: float64
y-intercept :  0    21.675596
Name: 1, dtype: float64
test_num :  526
slope :  0    1.005265
Name: 0, dtype: float64
y-intercept :  0    21.681311
Name: 1, dtype: float64
test_num :  527
slope :  0    1.00481
Name: 0, dtype: float64
y-intercept :  0    21.687
Name: 1, dtype: float64
test_num :  528
slope :  0    1.004356
Name: 0, dtype: float64
y-intercept :  0    21.692664
Name: 1, dtype: float64
test_num :  529
slope :  0    1.003905
Name: 0, dtype: float64
y-intercept :  0    21.698302
Name: 1, dtype: float64
test_num :  530
slope :  0    1.003455
Name: 0, dtype: float64
y-intercept :  0    21.703915
Name: 1, dtype: float64
test_num :  531
slope :  0    1.003008
Name: 0, dtype: float64
y-intercept :  0    21.709503
Name: 1, dtype: float64
test_num :  532
slope :  0    1.002562
Name: 0, dtype: float64
y-intercept :  0    21.715066
Name: 1, dtype: float64
test_num :  533
slope :  0    1.002119
Name: 0, dtype: float64
y-intercept :  0    21.720604
Name: 1, dtype: float64
test_num :  534
slope :  0    1.001677
Name: 0, dtype: float64
y-intercept :  0    21.726116
Name: 1, dtype: float64
test_num :  535
slope :  0    1.001238
Name: 0, dtype: float64
y-intercept :  0    21.731604
Name: 1, dtype: float64
test_num :  536
slope :  0    1.0008
Name: 0, dtype: float64
y-intercept :  0    21.737068
Name: 1, dtype: float64
test_num :  537
slope :  0    1.000365
Name: 0, dtype: float64
y-intercept :  0    21.742507
Name: 1, dtype: float64
test_num :  538
slope :  0    0.999931
Name: 0, dtype: float64
y-intercept :  0    21.747921
Name: 1, dtype: float64
test_num :  539
slope :  0    0.9995
Name: 0, dtype: float64
y-intercept :  0    21.753311
Name: 1, dtype: float64
test_num :  540
slope :  0    0.99907
Name: 0, dtype: float64
y-intercept :  0    21.758677
Name: 1, dtype: float64
test_num :  541
slope :  0    0.998642
Name: 0, dtype: float64
y-intercept :  0    21.764019
Name: 1, dtype: float64
test_num :  542
slope :  0    0.998216
Name: 0, dtype: float64
y-intercept :  0    21.769336
Name: 1, dtype: float64
test_num :  543
slope :  0    0.997792
Name: 0, dtype: float64
y-intercept :  0    21.77463
Name: 1, dtype: float64
test_num :  544
slope :  0    0.99737
Name: 0, dtype: float64
y-intercept :  0    21.7799
Name: 1, dtype: float64
test_num :  545
slope :  0    0.99695
Name: 0, dtype: float64
y-intercept :  0    21.785147
Name: 1, dtype: float64
test_num :  546
slope :  0    0.996532
Name: 0, dtype: float64
y-intercept :  0    21.790369
Name: 1, dtype: float64
test_num :  547
slope :  0    0.996116
Name: 0, dtype: float64
y-intercept :  0    21.795569
Name: 1, dtype: float64
test_num :  548
slope :  0    0.995701
Name: 0, dtype: float64
y-intercept :  0    21.800745
Name: 1, dtype: float64
test_num :  549
slope :  0    0.995289
Name: 0, dtype: float64
y-intercept :  0    21.805897
Name: 1, dtype: float64
test_num :  550
slope :  0    0.994878
Name: 0, dtype: float64
y-intercept :  0    21.811027
Name: 1, dtype: float64
test_num :  551
slope :  0    0.994469
Name: 0, dtype: float64
y-intercept :  0    21.816133
Name: 1, dtype: float64
test_num :  552
slope :  0    0.994062
Name: 0, dtype: float64
y-intercept :  0    21.821217
Name: 1, dtype: float64
test_num :  553
slope :  0    0.993656
Name: 0, dtype: float64
y-intercept :  0    21.826278
Name: 1, dtype: float64
test_num :  554
slope :  0    0.993253
Name: 0, dtype: float64
y-intercept :  0    21.831316
Name: 1, dtype: float64
test_num :  555
slope :  0    0.992851
Name: 0, dtype: float64
y-intercept :  0    21.836331
Name: 1, dtype: float64
test_num :  556
slope :  0    0.992452
Name: 0, dtype: float64
y-intercept :  0    21.841324
Name: 1, dtype: float64
test_num :  557
slope :  0    0.992054
Name: 0, dtype: float64
y-intercept :  0    21.846294
Name: 1, dtype: float64
test_num :  558
slope :  0    0.991657
Name: 0, dtype: float64
y-intercept :  0    21.851242
Name: 1, dtype: float64
test_num :  559
slope :  0    0.991263
Name: 0, dtype: float64
y-intercept :  0    21.856168
Name: 1, dtype: float64
test_num :  560
slope :  0    0.99087
Name: 0, dtype: float64
y-intercept :  0    21.861072
Name: 1, dtype: float64
test_num :  561
slope :  0    0.990479
Name: 0, dtype: float64
y-intercept :  0    21.865953
Name: 1, dtype: float64
test_num :  562
slope :  0    0.99009
Name: 0, dtype: float64
y-intercept :  0    21.870813
Name: 1, dtype: float64
test_num :  563
slope :  0    0.989703
Name: 0, dtype: float64
y-intercept :  0    21.875651

Name: 1, dtype: float64
test_num :  564
slope :  0    0.989317
Name: 0, dtype: float64
y-intercept :  0    21.880467
Name: 1, dtype: float64
test_num :  565
slope :  0    0.988933
Name: 0, dtype: float64
y-intercept :  0    21.885262
Name: 1, dtype: float64
test_num :  566
slope :  0    0.988551
Name: 0, dtype: float64
y-intercept :  0    21.890035
Name: 1, dtype: float64
test_num :  567
slope :  0    0.98817
Name: 0, dtype: float64
y-intercept :  0    21.894786
Name: 1, dtype: float64
test_num :  568
slope :  0    0.987792
Name: 0, dtype: float64
y-intercept :  0    21.899516
Name: 1, dtype: float64
test_num :  569
slope :  0    0.987415
Name: 0, dtype: float64
y-intercept :  0    21.904225
Name: 1, dtype: float64
test_num :  570
slope :  0    0.987039
Name: 0, dtype: float64
y-intercept :  0    21.908913
Name: 1, dtype: float64
test_num :  571
slope :  0    0.986665
Name: 0, dtype: float64
y-intercept :  0    21.91358
Name: 1, dtype: float64
test_num :  572
slope :  0    0.986293
Name: 0, dtype: float64
y-intercept :  0    21.918226
Name: 1, dtype: float64
test_num :  573
slope :  0    0.985923
Name: 0, dtype: float64
y-intercept :  0    21.92285
Name: 1, dtype: float64
test_num :  574
slope :  0    0.985554
Name: 0, dtype: float64
y-intercept :  0    21.927454
Name: 1, dtype: float64
test_num :  575
slope :  0    0.985187
Name: 0, dtype: float64
y-intercept :  0    21.932038
Name: 1, dtype: float64
test_num :  576
slope :  0    0.984822
Name: 0, dtype: float64
y-intercept :  0    21.936601
Name: 1, dtype: float64
test_num :  577
slope :  0    0.984458
Name: 0, dtype: float64
y-intercept :  0    21.941143
Name: 1, dtype: float64
test_num :  578
slope :  0    0.984096
Name: 0, dtype: float64
y-intercept :  0    21.945665
Name: 1, dtype: float64
test_num :  579
slope :  0    0.983736
Name: 0, dtype: float64
y-intercept :  0    21.950166
Name: 1, dtype: float64
test_num :  580
slope :  0    0.983377
Name: 0, dtype: float64
y-intercept :  0    21.954648
Name: 1, dtype: float64
test_num :  581
slope :  0    0.983019
Name: 0, dtype: float64
y-intercept :  0    21.959109
Name: 1, dtype: float64
test_num :  582
slope :  0    0.982664
Name: 0, dtype: float64
y-intercept :  0    21.96355
Name: 1, dtype: float64
test_num :  583
slope :  0    0.98231
Name: 0, dtype: float64
y-intercept :  0    21.967971
Name: 1, dtype: float64
test_num :  584
slope :  0    0.981957
Name: 0, dtype: float64
y-intercept :  0    21.972373
Name: 1, dtype: float64
test_num :  585
slope :  0    0.981606
Name: 0, dtype: float64
y-intercept :  0    21.976754
Name: 1, dtype: float64
test_num :  586
slope :  0    0.981257
Name: 0, dtype: float64
y-intercept :  0    21.981116
Name: 1, dtype: float64
test_num :  587
slope :  0    0.980909
Name: 0, dtype: float64
y-intercept :  0    21.985458
Name: 1, dtype: float64
test_num :  588
slope :  0    0.980563
Name: 0, dtype: float64
y-intercept :  0    21.989781
Name: 1, dtype: float64
test_num :  589
slope :  0    0.980219
Name: 0, dtype: float64
y-intercept :  0    21.994085
Name: 1, dtype: float64
test_num :  590
slope :  0    0.979876
Name: 0, dtype: float64
y-intercept :  0    21.998369
Name: 1, dtype: float64
test_num :  591
slope :  0    0.979534
Name: 0, dtype: float64
y-intercept :  0    22.002633
Name: 1, dtype: float64
test_num :  592
slope :  0    0.979194
Name: 0, dtype: float64
y-intercept :  0    22.006879
Name: 1, dtype: float64
test_num :  593
slope :  0    0.978856
Name: 0, dtype: float64
y-intercept :  0    22.011105
Name: 1, dtype: float64
test_num :  594
slope :  0    0.978519
Name: 0, dtype: float64
y-intercept :  0    22.015313
Name: 1, dtype: float64
test_num :  595
slope :  0    0.978183
Name: 0, dtype: float64
y-intercept :  0    22.019502
Name: 1, dtype: float64
test_num :  596
slope :  0    0.977849
Name: 0, dtype: float64
y-intercept :  0    22.023671
Name: 1, dtype: float64
test_num :  597
slope :  0    0.977517
Name: 0, dtype: float64
y-intercept :  0    22.027823
Name: 1, dtype: float64
test_num :  598
slope :  0    0.977186
Name: 0, dtype: float64
y-intercept :  0    22.031955
Name: 1, dtype: float64
test_num :  599
slope :  0    0.976857
Name: 0, dtype: float64
y-intercept :  0    22.036069
Name: 1, dtype: float64
test_num :  600
slope :  0    0.976529
Name: 0, dtype: float64
y-intercept :  0    22.040164
Name: 1, dtype: float64
test_num :  601
slope :  0    0.976202
Name: 0, dtype: float64
y-intercept :  0    22.044241
Name: 1, dtype: float64
test_num :  602
slope :  0    0.975877
Name: 0, dtype: float64
y-intercept :  0    22.0483
Name: 1, dtype: float64
test_num :  603
slope :  0    0.975554
Name: 0, dtype: float64
y-intercept :  0    22.05234
Name: 1, dtype: float64
test_num :  604
slope :  0    0.975232
Name: 0, dtype: float64
y-intercept :  0    22.056363
Name: 1, dtype: float64
test_num :  605
slope :  0    0.974911
Name: 0, dtype: float64
y-intercept :  0    22.060367
Name: 1, dtype: float64
test_num :  606
slope :  0    0.974592
Name: 0, dtype: float64
y-intercept :  0    22.064353
Name: 1, dtype: float64
test_num :  607
slope :  0    0.974274
Name: 0, dtype: float64
y-intercept :  0    22.068321
Name: 1, dtype: float64
test_num :  608
slope :  0    0.973958
Name: 0, dtype: float64
y-intercept :  0    22.072272
Name: 1, dtype: float64
test_num :  609
slope :  0    0.973643
Name: 0, dtype: float64
y-intercept :  0    22.076204
Name: 1, dtype: float64
test_num :  610
slope :  0    0.973329
Name: 0, dtype: float64
y-intercept :  0    22.080119
Name: 1, dtype: float64
test_num :  611
slope :  0    0.973017
Name: 0, dtype: float64
y-intercept :  0    22.084017
Name: 1, dtype: float64
test_num :  612
slope :  0    0.972706
Name: 0, dtype: float64
y-intercept :  0    22.087897
Name: 1, dtype: float64
test_num :  613
slope :  0    0.972397
Name: 0, dtype: float64
y-intercept :  0    22.091759
Name: 1, dtype: float64
test_num :  614
slope :  0    0.972089
Name: 0, dtype: float64
y-intercept :  0    22.095605
Name: 1, dtype: float64
test_num :  615
slope :  0    0.971783
Name: 0, dtype: float64
y-intercept :  0    22.099432
Name: 1, dtype: float64
test_num :  616
slope :  0    0.971477
Name: 0, dtype: float64
y-intercept :  0    22.103243
Name: 1, dtype: float64
test_num :  617
slope :  0    0.971174
Name: 0, dtype: float64
y-intercept :  0    22.107037
Name: 1, dtype: float64
test_num :  618
slope :  0    0.970871
Name: 0, dtype: float64
y-intercept :  0    22.110813
Name: 1, dtype: float64
test_num :  619
slope :  0    0.97057
Name: 0, dtype: float64
y-intercept :  0    22.114573
Name: 1, dtype: float64
test_num :  620
slope :  0    0.97027
Name: 0, dtype: float64
y-intercept :  0    22.118315
Name: 1, dtype: float64
test_num :  621
slope :  0    0.969972
Name: 0, dtype: float64
y-intercept :  0    22.122041
Name: 1, dtype: float64
test_num :  622
slope :  0    0.969675
Name: 0, dtype: float64
y-intercept :  0    22.12575
Name: 1, dtype: float64
test_num :  623
slope :  0    0.969379
Name: 0, dtype: float64
y-intercept :  0    22.129443
Name: 1, dtype: float64
test_num :  624
slope :  0    0.969085
Name: 0, dtype: float64
y-intercept :  0    22.133119
Name: 1, dtype: float64
test_num :  625
slope :  0    0.968792
Name: 0, dtype: float64
y-intercept :  0    22.136778
Name: 1, dtype: float64
test_num :  626
slope :  0    0.9685
Name: 0, dtype: float64
y-intercept :  0    22.140421
Name: 1, dtype: float64
test_num :  627
slope :  0    0.96821
Name: 0, dtype: float64
y-intercept :  0    22.144047
Name: 1, dtype: float64
test_num :  628
slope :  0    0.967921
Name: 0, dtype: float64
y-intercept :  0    22.147658
Name: 1, dtype: float64
test_num :  629
slope :  0    0.967633
Name: 0, dtype: float64
y-intercept :  0    22.151252
Name: 1, dtype: float64
test_num :  630
slope :  0    0.967346
Name: 0, dtype: float64
y-intercept :  0    22.154829
Name: 1, dtype: float64
test_num :  631
slope :  0    0.967061
Name: 0, dtype: float64
y-intercept :  0    22.158391
Name: 1, dtype: float64
test_num :  632
slope :  0    0.966777
Name: 0, dtype: float64
y-intercept :  0    22.161937
Name: 1, dtype: float64
test_num :  633
slope :  0    0.966495
Name: 0, dtype: float64
y-intercept :  0    22.165467
Name: 1, dtype: float64
test_num :  634
slope :  0    0.966213
Name: 0, dtype: float64
y-intercept :  0    22.168981
Name: 1, dtype: float64
test_num :  635
slope :  0    0.965933
Name: 0, dtype: float64
y-intercept :  0    22.172479
Name: 1, dtype: float64
test_num :  636
slope :  0    0.965654
Name: 0, dtype: float64
y-intercept :  0    22.175961
Name: 1, dtype: float64
test_num :  637
slope :  0    0.965377
Name: 0, dtype: float64
y-intercept :  0    22.179428
Name: 1, dtype: float64
test_num :  638
slope :  0    0.9651
Name: 0, dtype: float64
y-intercept :  0    22.18288
Name: 1, dtype: float64
test_num :  639
slope :  0    0.964825
Name: 0, dtype: float64
y-intercept :  0    22.186315
Name: 1, dtype: float64
test_num :  640
slope :  0    0.964551
Name: 0, dtype: float64
y-intercept :  0    22.189736
Name: 1, dtype: float64
test_num :  641
slope :  0    0.964278
Name: 0, dtype: float64
y-intercept :  0    22.193141
Name: 1, dtype: float64
test_num :  642
slope :  0    0.964007
Name: 0, dtype: float64
y-intercept :  0    22.19653
Name: 1, dtype: float64
test_num :  643
slope :  0    0.963737
Name: 0, dtype: float64
y-intercept :  0    22.199905
Name: 1, dtype: float64
test_num :  644
slope :  0    0.963468
Name: 0, dtype: float64
y-intercept :  0    22.203264
Name: 1, dtype: float64
test_num :  645
slope :  0    0.9632
Name: 0, dtype: float64
y-intercept :  0    22.206608
Name: 1, dtype: float64
test_num :  646
slope :  0    0.962933
Name: 0, dtype: float64
y-intercept :  0    22.209937
Name: 1, dtype: float64
test_num :  647
slope :  0    0.962668
Name: 0, dtype: float64
y-intercept :  0    22.213251
Name: 1, dtype: float64
test_num :  648
slope :  0    0.962404
Name: 0, dtype: float64
y-intercept :  0    22.216551
Name: 1, dtype: float64
test_num :  649
slope :  0    0.962141
Name: 0, dtype: float64
y-intercept :  0    22.219835
Name: 1, dtype: float64
test_num :  650
slope :  0    0.961879
Name: 0, dtype: float64
y-intercept :  0    22.223105
Name: 1, dtype: float64
test_num :  651
slope :  0    0.961618
Name: 0, dtype: float64
y-intercept :  0    22.22636
Name: 1, dtype: float64
test_num :  652
slope :  0    0.961359
Name: 0, dtype: float64
y-intercept :  0    22.2296
Name: 1, dtype: float64
test_num :  653
slope :  0    0.961101
Name: 0, dtype: float64
y-intercept :  0    22.232826
Name: 1, dtype: float64
test_num :  654
slope :  0    0.960843
Name: 0, dtype: float64
y-intercept :  0    22.236037
Name: 1, dtype: float64
test_num :  655
slope :  0    0.960587
Name: 0, dtype: float64
y-intercept :  0    22.239234
Name: 1, dtype: float64
test_num :  656
slope :  0    0.960332
Name: 0, dtype: float64
y-intercept :  0    22.242417
Name: 1, dtype: float64
test_num :  657
slope :  0    0.960079
Name: 0, dtype: float64
y-intercept :  0    22.245585
Name: 1, dtype: float64
test_num :  658
slope :  0    0.959826
Name: 0, dtype: float64
y-intercept :  0    22.248739
Name: 1, dtype: float64
test_num :  659
slope :  0    0.959575
Name: 0, dtype: float64
y-intercept :  0    22.251879
Name: 1, dtype: float64
test_num :  660
slope :  0    0.959324
Name: 0, dtype: float64
y-intercept :  0    22.255005
Name: 1, dtype: float64
test_num :  661
slope :  0    0.959075
Name: 0, dtype: float64
y-intercept :  0    22.258116
Name: 1, dtype: float64
test_num :  662
slope :  0    0.958827
Name: 0, dtype: float64
y-intercept :  0    22.261214
Name: 1, dtype: float64
test_num :  663
slope :  0    0.95858
Name: 0, dtype: float64
y-intercept :  0    22.264298
Name: 1, dtype: float64
test_num :  664
slope :  0    0.958334
Name: 0, dtype: float64
y-intercept :  0    22.267368
Name: 1, dtype: float64
test_num :  665
slope :  0    0.95809
Name: 0, dtype: float64
y-intercept :  0    22.270424
Name: 1, dtype: float64
test_num :  666
slope :  0    0.957846
Name: 0, dtype: float64
y-intercept :  0    22.273466
Name: 1, dtype: float64
test_num :  667
slope :  0    0.957604
Name: 0, dtype: float64
y-intercept :  0    22.276495
Name: 1, dtype: float64
test_num :  668
slope :  0    0.957362
Name: 0, dtype: float64
y-intercept :  0    22.27951
Name: 1, dtype: float64
test_num :  669
slope :  0    0.957122
Name: 0, dtype: float64
y-intercept :  0    22.282512
Name: 1, dtype: float64
test_num :  670
slope :  0    0.956882
Name: 0, dtype: float64
y-intercept :  0    22.2855
Name: 1, dtype: float64
test_num :  671
slope :  0    0.956644
Name: 0, dtype: float64
y-intercept :  0    22.288474
Name: 1, dtype: float64
test_num :  672
slope :  0    0.956407
Name: 0, dtype: float64
y-intercept :  0    22.291436
Name: 1, dtype: float64
test_num :  673
slope :  0    0.956171
Name: 0, dtype: float64
y-intercept :  0    22.294384
Name: 1, dtype: float64
test_num :  674
slope :  0    0.955936
Name: 0, dtype: float64
y-intercept :  0    22.297318
Name: 1, dtype: float64
test_num :  675
slope :  0    0.955702
Name: 0, dtype: float64
y-intercept :  0    22.30024
Name: 1, dtype: float64
test_num :  676
slope :  0    0.955469
Name: 0, dtype: float64
y-intercept :  0    22.303148
Name: 1, dtype: float64
test_num :  677
slope :  0    0.955237
Name: 0, dtype: float64
y-intercept :  0    22.306044
Name: 1, dtype: float64
test_num :  678
slope :  0    0.955006
Name: 0, dtype: float64
y-intercept :  0    22.308926
Name: 1, dtype: float64
test_num :  679
slope :  0    0.954777
Name: 0, dtype: float64
y-intercept :  0    22.311795
Name: 1, dtype: float64
test_num :  680
slope :  0    0.954548
Name: 0, dtype: float64
y-intercept :  0    22.314652
Name: 1, dtype: float64
test_num :  681
slope :  0    0.95432
Name: 0, dtype: float64
y-intercept :  0    22.317496
Name: 1, dtype: float64
test_num :  682
slope :  0    0.954094
Name: 0, dtype: float64
y-intercept :  0    22.320327
Name: 1, dtype: float64
test_num :  683
slope :  0    0.953868
Name: 0, dtype: float64
y-intercept :  0    22.323145
Name: 1, dtype: float64
test_num :  684
slope :  0    0.953643
Name: 0, dtype: float64
y-intercept :  0    22.32595
Name: 1, dtype: float64
test_num :  685
slope :  0    0.95342
Name: 0, dtype: float64
y-intercept :  0    22.328743
Name: 1, dtype: float64
test_num :  686
slope :  0    0.953197
Name: 0, dtype: float64
y-intercept :  0    22.331524
Name: 1, dtype: float64
test_num :  687
slope :  0    0.952975
Name: 0, dtype: float64
y-intercept :  0    22.334291
Name: 1, dtype: float64
test_num :  688
slope :  0    0.952755
Name: 0, dtype: float64
y-intercept :  0    22.337047
Name: 1, dtype: float64
test_num :  689
slope :  0    0.952535
Name: 0, dtype: float64
y-intercept :  0    22.33979
Name: 1, dtype: float64
test_num :  690
slope :  0    0.952316
Name: 0, dtype: float64
y-intercept :  0    22.342521
Name: 1, dtype: float64
test_num :  691
slope :  0    0.952099
Name: 0, dtype: float64
y-intercept :  0    22.345239
Name: 1, dtype: float64
test_num :  692
slope :  0    0.951882
Name: 0, dtype: float64
y-intercept :  0    22.347945
Name: 1, dtype: float64
test_num :  693
slope :  0    0.951666
Name: 0, dtype: float64
y-intercept :  0    22.350639
Name: 1, dtype: float64
test_num :  694
slope :  0    0.951451
Name: 0, dtype: float64
y-intercept :  0    22.353321
Name: 1, dtype: float64
test_num :  695
slope :  0    0.951238
Name: 0, dtype: float64
y-intercept :  0    22.355991
Name: 1, dtype: float64
test_num :  696
slope :  0    0.951025
Name: 0, dtype: float64
y-intercept :  0    22.358649
Name: 1, dtype: float64
test_num :  697
slope :  0    0.950813
Name: 0, dtype: float64
y-intercept :  0    22.361295
Name: 1, dtype: float64
test_num :  698
slope :  0    0.950602
Name: 0, dtype: float64
y-intercept :  0    22.363929
Name: 1, dtype: float64
test_num :  699
slope :  0    0.950392
Name: 0, dtype: float64
y-intercept :  0    22.366552
Name: 1, dtype: float64
test_num :  700
slope :  0    0.950183
Name: 0, dtype: float64
y-intercept :  0    22.369162
Name: 1, dtype: float64
test_num :  701
slope :  0    0.949975
Name: 0, dtype: float64
y-intercept :  0    22.371761
Name: 1, dtype: float64
test_num :  702
slope :  0    0.949768
Name: 0, dtype: float64
y-intercept :  0    22.374348
Name: 1, dtype: float64
test_num :  703
slope :  0    0.949561
Name: 0, dtype: float64
y-intercept :  0    22.376923
Name: 1, dtype: float64
test_num :  704
slope :  0    0.949356
Name: 0, dtype: float64
y-intercept :  0    22.379487
Name: 1, dtype: float64
test_num :  705
slope :  0    0.949152
Name: 0, dtype: float64
y-intercept :  0    22.38204
Name: 1, dtype: float64
test_num :  706
slope :  0    0.948948
Name: 0, dtype: float64
y-intercept :  0    22.384581
Name: 1, dtype: float64
test_num :  707
slope :  0    0.948746
Name: 0, dtype: float64
y-intercept :  0    22.38711
Name: 1, dtype: float64
test_num :  708
slope :  0    0.948544
Name: 0, dtype: float64
y-intercept :  0    22.389628
Name: 1, dtype: float64
test_num :  709
slope :  0    0.948343
Name: 0, dtype: float64
y-intercept :  0    22.392135
Name: 1, dtype: float64
test_num :  710
slope :  0    0.948143
Name: 0, dtype: float64
y-intercept :  0    22.394631
Name: 1, dtype: float64
test_num :  711
slope :  0    0.947944
Name: 0, dtype: float64
y-intercept :  0    22.397115
Name: 1, dtype: float64
test_num :  712
slope :  0    0.947746
Name: 0, dtype: float64
y-intercept :  0    22.399588
Name: 1, dtype: float64
test_num :  713
slope :  0    0.947549
Name: 0, dtype: float64
y-intercept :  0    22.40205
Name: 1, dtype: float64
test_num :  714
slope :  0    0.947353
Name: 0, dtype: float64
y-intercept :  0    22.404501
Name: 1, dtype: float64
test_num :  715
slope :  0    0.947158
Name: 0, dtype: float64
y-intercept :  0    22.406941
Name: 1, dtype: float64
test_num :  716
slope :  0    0.946963
Name: 0, dtype: float64
y-intercept :  0    22.40937
Name: 1, dtype: float64
test_num :  717
slope :  0    0.946769
Name: 0, dtype: float64
y-intercept :  0    22.411788
Name: 1, dtype: float64
test_num :  718
slope :  0    0.946577
Name: 0, dtype: float64
y-intercept :  0    22.414195
Name: 1, dtype: float64
test_num :  719
slope :  0    0.946385
Name: 0, dtype: float64
y-intercept :  0    22.416592
Name: 1, dtype: float64
test_num :  720
slope :  0    0.946194
Name: 0, dtype: float64
y-intercept :  0    22.418978
Name: 1, dtype: float64
test_num :  721
slope :  0    0.946003
Name: 0, dtype: float64
y-intercept :  0    22.421352
Name: 1, dtype: float64
test_num :  722
slope :  0    0.945814
Name: 0, dtype: float64
y-intercept :  0    22.423717
Name: 1, dtype: float64
test_num :  723
slope :  0    0.945626
Name: 0, dtype: float64
y-intercept :  0    22.42607
Name: 1, dtype: float64
test_num :  724
slope :  0    0.945438
Name: 0, dtype: float64
y-intercept :  0    22.428413
Name: 1, dtype: float64
test_num :  725
slope :  0    0.945251
Name: 0, dtype: float64
y-intercept :  0    22.430746
Name: 1, dtype: float64
test_num :  726
slope :  0    0.945065
Name: 0, dtype: float64
y-intercept :  0    22.433068
Name: 1, dtype: float64
test_num :  727
slope :  0    0.94488
Name: 0, dtype: float64
y-intercept :  0    22.43538
Name: 1, dtype: float64
test_num :  728
slope :  0    0.944696
Name: 0, dtype: float64
y-intercept :  0    22.437681
Name: 1, dtype: float64

test_num :  729
slope :  0    0.944512
Name: 0, dtype: float64
y-intercept :  0    22.439972
Name: 1, dtype: float64
test_num :  730
slope :  0    0.94433
Name: 0, dtype: float64
y-intercept :  0    22.442252
Name: 1, dtype: float64
test_num :  731
slope :  0    0.944148
Name: 0, dtype: float64
y-intercept :  0    22.444523
Name: 1, dtype: float64
test_num :  732
slope :  0    0.943967
Name: 0, dtype: float64
y-intercept :  0    22.446783
Name: 1, dtype: float64
test_num :  733
slope :  0    0.943787
Name: 0, dtype: float64
y-intercept :  0    22.449033
Name: 1, dtype: float64
test_num :  734
slope :  0    0.943608
Name: 0, dtype: float64
y-intercept :  0    22.451273
Name: 1, dtype: float64
test_num :  735
slope :  0    0.943429
Name: 0, dtype: float64
y-intercept :  0    22.453503
Name: 1, dtype: float64
test_num :  736
slope :  0    0.943251
Name: 0, dtype: float64
y-intercept :  0    22.455722
Name: 1, dtype: float64
test_num :  737
slope :  0    0.943074
Name: 0, dtype: float64
y-intercept :  0    22.457932
Name: 1, dtype: float64
test_num :  738
slope :  0    0.942898
Name: 0, dtype: float64
y-intercept :  0    22.460132
Name: 1, dtype: float64
test_num :  739
slope :  0    0.942723
Name: 0, dtype: float64
y-intercept :  0    22.462322
Name: 1, dtype: float64
test_num :  740
slope :  0    0.942548
Name: 0, dtype: float64
y-intercept :  0    22.464502
Name: 1, dtype: float64
test_num :  741
slope :  0    0.942374
Name: 0, dtype: float64
y-intercept :  0    22.466673
Name: 1, dtype: float64
test_num :  742
slope :  0    0.942201
Name: 0, dtype: float64
y-intercept :  0    22.468833
Name: 1, dtype: float64
test_num :  743
slope :  0    0.942029
Name: 0, dtype: float64
y-intercept :  0    22.470984
Name: 1, dtype: float64
test_num :  744
slope :  0    0.941858
Name: 0, dtype: float64
y-intercept :  0    22.473126
Name: 1, dtype: float64
test_num :  745
slope :  0    0.941687
Name: 0, dtype: float64
y-intercept :  0    22.475257
Name: 1, dtype: float64
test_num :  746
slope :  0    0.941517
Name: 0, dtype: float64
y-intercept :  0    22.477379
Name: 1, dtype: float64
test_num :  747
slope :  0    0.941348
Name: 0, dtype: float64
y-intercept :  0    22.479492
Name: 1, dtype: float64
test_num :  748
slope :  0    0.941179
Name: 0, dtype: float64
y-intercept :  0    22.481595
Name: 1, dtype: float64
test_num :  749
slope :  0    0.941012
Name: 0, dtype: float64
y-intercept :  0    22.483688
Name: 1, dtype: float64
test_num :  750
slope :  0    0.940845
Name: 0, dtype: float64
y-intercept :  0    22.485773
Name: 1, dtype: float64
test_num :  751
slope :  0    0.940679
Name: 0, dtype: float64
y-intercept :  0    22.487847
Name: 1, dtype: float64
test_num :  752
slope :  0    0.940513
Name: 0, dtype: float64
y-intercept :  0    22.489913
Name: 1, dtype: float64
test_num :  753
slope :  0    0.940349
Name: 0, dtype: float64
y-intercept :  0    22.491969
Name: 1, dtype: float64
test_num :  754
slope :  0    0.940185
Name: 0, dtype: float64
y-intercept :  0    22.494016
Name: 1, dtype: float64
test_num :  755
slope :  0    0.940021
Name: 0, dtype: float64
y-intercept :  0    22.496054
Name: 1, dtype: float64
test_num :  756
slope :  0    0.939859
Name: 0, dtype: float64
y-intercept :  0    22.498083
Name: 1, dtype: float64
test_num :  757
slope :  0    0.939697
Name: 0, dtype: float64
y-intercept :  0    22.500102
Name: 1, dtype: float64
test_num :  758
slope :  0    0.939536
Name: 0, dtype: float64
y-intercept :  0    22.502113
Name: 1, dtype: float64
test_num :  759
slope :  0    0.939376
Name: 0, dtype: float64
y-intercept :  0    22.504114
Name: 1, dtype: float64
test_num :  760
slope :  0    0.939216
Name: 0, dtype: float64
y-intercept :  0    22.506106
Name: 1, dtype: float64
test_num :  761
slope :  0    0.939058
Name: 0, dtype: float64
y-intercept :  0    22.50809
Name: 1, dtype: float64
test_num :  762
slope :  0    0.9389
Name: 0, dtype: float64
y-intercept :  0    22.510064
Name: 1, dtype: float64
test_num :  763
slope :  0    0.938742
Name: 0, dtype: float64
y-intercept :  0    22.51203
Name: 1, dtype: float64
test_num :  764
slope :  0    0.938585
Name: 0, dtype: float64
y-intercept :  0    22.513987
Name: 1, dtype: float64
test_num :  765
slope :  0    0.938429
Name: 0, dtype: float64
y-intercept :  0    22.515935
Name: 1, dtype: float64
test_num :  766
slope :  0    0.938274
Name: 0, dtype: float64
y-intercept :  0    22.517874
Name: 1, dtype: float64
test_num :  767
slope :  0    0.93812
Name: 0, dtype: float64
y-intercept :  0    22.519805
Name: 1, dtype: float64
test_num :  768
slope :  0    0.937966
Name: 0, dtype: float64
y-intercept :  0    22.521727
Name: 1, dtype: float64
test_num :  769
slope :  0    0.937812
Name: 0, dtype: float64
y-intercept :  0    22.52364
Name: 1, dtype: float64
test_num :  770
slope :  0    0.93766
Name: 0, dtype: float64
y-intercept :  0    22.525545
Name: 1, dtype: float64
test_num :  771
slope :  0    0.937508
Name: 0, dtype: float64
y-intercept :  0    22.527441
Name: 1, dtype: float64
test_num :  772
slope :  0    0.937357
Name: 0, dtype: float64
y-intercept :  0    22.529328
Name: 1, dtype: float64
test_num :  773
slope :  0    0.937206
Name: 0, dtype: float64
y-intercept :  0    22.531207
Name: 1, dtype: float64
test_num :  774
slope :  0    0.937057
Name: 0, dtype: float64
y-intercept :  0    22.533078
Name: 1, dtype: float64
test_num :  775
slope :  0    0.936907
Name: 0, dtype: float64
y-intercept :  0    22.53494
Name: 1, dtype: float64
test_num :  776
slope :  0    0.936759
Name: 0, dtype: float64
y-intercept :  0    22.536794
Name: 1, dtype: float64
test_num :  777
slope :  0    0.936611
Name: 0, dtype: float64
y-intercept :  0    22.53864
Name: 1, dtype: float64
test_num :  778
slope :  0    0.936464
Name: 0, dtype: float64
y-intercept :  0    22.540477
Name: 1, dtype: float64
test_num :  779
slope :  0    0.936318
Name: 0, dtype: float64
y-intercept :  0    22.542306
Name: 1, dtype: float64
test_num :  780
slope :  0    0.936172
Name: 0, dtype: float64
y-intercept :  0    22.544127
Name: 1, dtype: float64
test_num :  781
slope :  0    0.936027
Name: 0, dtype: float64
y-intercept :  0    22.54594
Name: 1, dtype: float64
test_num :  782
slope :  0    0.935882
Name: 0, dtype: float64
y-intercept :  0    22.547744
Name: 1, dtype: float64
test_num :  783
slope :  0    0.935738
Name: 0, dtype: float64
y-intercept :  0    22.549541
Name: 1, dtype: float64
test_num :  784
slope :  0    0.935595
Name: 0, dtype: float64
y-intercept :  0    22.551329
Name: 1, dtype: float64
test_num :  785
slope :  0    0.935453
Name: 0, dtype: float64
y-intercept :  0    22.553109
Name: 1, dtype: float64
test_num :  786
slope :  0    0.935311
Name: 0, dtype: float64
y-intercept :  0    22.554881
Name: 1, dtype: float64
test_num :  787
slope :  0    0.935169
Name: 0, dtype: float64
y-intercept :  0    22.556646
Name: 1, dtype: float64
test_num :  788
slope :  0    0.935029
Name: 0, dtype: float64
y-intercept :  0    22.558402
Name: 1, dtype: float64
test_num :  789
slope :  0    0.934889
Name: 0, dtype: float64
y-intercept :  0    22.560151
Name: 1, dtype: float64
test_num :  790
slope :  0    0.934749
Name: 0, dtype: float64
y-intercept :  0    22.561891
Name: 1, dtype: float64
test_num :  791
slope :  0    0.934611
Name: 0, dtype: float64
y-intercept :  0    22.563624
Name: 1, dtype: float64
test_num :  792
slope :  0    0.934472
Name: 0, dtype: float64
y-intercept :  0    22.565349
Name: 1, dtype: float64
test_num :  793
slope :  0    0.934335
Name: 0, dtype: float64
y-intercept :  0    22.567066
Name: 1, dtype: float64
test_num :  794
slope :  0    0.934198
Name: 0, dtype: float64
y-intercept :  0    22.568776
Name: 1, dtype: float64
test_num :  795
slope :  0    0.934062
Name: 0, dtype: float64
y-intercept :  0    22.570478
Name: 1, dtype: float64
test_num :  796
slope :  0    0.933926
Name: 0, dtype: float64
y-intercept :  0    22.572172
Name: 1, dtype: float64
test_num :  797
slope :  0    0.933791
Name: 0, dtype: float64
y-intercept :  0    22.573859
Name: 1, dtype: float64
test_num :  798
slope :  0    0.933657
Name: 0, dtype: float64
y-intercept :  0    22.575538
Name: 1, dtype: float64
test_num :  799
slope :  0    0.933523
Name: 0, dtype: float64
y-intercept :  0    22.577209
Name: 1, dtype: float64
test_num :  800
slope :  0    0.933389
Name: 0, dtype: float64
y-intercept :  0    22.578873
Name: 1, dtype: float64
test_num :  801
slope :  0    0.933257
Name: 0, dtype: float64
y-intercept :  0    22.58053
Name: 1, dtype: float64
test_num :  802
slope :  0    0.933125
Name: 0, dtype: float64
y-intercept :  0    22.582179
Name: 1, dtype: float64
test_num :  803
slope :  0    0.932993
Name: 0, dtype: float64
y-intercept :  0    22.58382
Name: 1, dtype: float64
test_num :  804
slope :  0    0.932862
Name: 0, dtype: float64
y-intercept :  0    22.585455
Name: 1, dtype: float64
test_num :  805
slope :  0    0.932732
Name: 0, dtype: float64
y-intercept :  0    22.587082
Name: 1, dtype: float64
test_num :  806
slope :  0    0.932602
Name: 0, dtype: float64
y-intercept :  0    22.588701
Name: 1, dtype: float64
test_num :  807
slope :  0    0.932473
Name: 0, dtype: float64
y-intercept :  0    22.590314
Name: 1, dtype: float64
test_num :  808
slope :  0    0.932345
Name: 0, dtype: float64
y-intercept :  0    22.591919
Name: 1, dtype: float64
test_num :  809
slope :  0    0.932217
Name: 0, dtype: float64
y-intercept :  0    22.593517
Name: 1, dtype: float64
test_num :  810
slope :  0    0.932089
Name: 0, dtype: float64
y-intercept :  0    22.595107
Name: 1, dtype: float64
test_num :  811
slope :  0    0.931963
Name: 0, dtype: float64
y-intercept :  0    22.596691
Name: 1, dtype: float64
test_num :  812
slope :  0    0.931836
Name: 0, dtype: float64
y-intercept :  0    22.598267
Name: 1, dtype: float64
test_num :  813
slope :  0    0.931711
Name: 0, dtype: float64
y-intercept :  0    22.599837
Name: 1, dtype: float64
test_num :  814
slope :  0    0.931586
Name: 0, dtype: float64
y-intercept :  0    22.601399
Name: 1, dtype: float64
test_num :  815
slope :  0    0.931461
Name: 0, dtype: float64
y-intercept :  0    22.602954
Name: 1, dtype: float64
test_num :  816
slope :  0    0.931337
Name: 0, dtype: float64
y-intercept :  0    22.604503
Name: 1, dtype: float64
test_num :  817
slope :  0    0.931214
Name: 0, dtype: float64
y-intercept :  0    22.606044
Name: 1, dtype: float64
test_num :  818
slope :  0    0.931091
Name: 0, dtype: float64
y-intercept :  0    22.607578
Name: 1, dtype: float64
test_num :  819
slope :  0    0.930968
Name: 0, dtype: float64
y-intercept :  0    22.609106
Name: 1, dtype: float64
test_num :  820
slope :  0    0.930847
Name: 0, dtype: float64
y-intercept :  0    22.610627
Name: 1, dtype: float64
test_num :  821
slope :  0    0.930725
Name: 0, dtype: float64
y-intercept :  0    22.61214
Name: 1, dtype: float64
test_num :  822
slope :  0    0.930605
Name: 0, dtype: float64
y-intercept :  0    22.613647
Name: 1, dtype: float64
test_num :  823
slope :  0    0.930485
Name: 0, dtype: float64
y-intercept :  0    22.615148
Name: 1, dtype: float64
test_num :  824
slope :  0    0.930365
Name: 0, dtype: float64
y-intercept :  0    22.616641
Name: 1, dtype: float64
test_num :  825
slope :  0    0.930246
Name: 0, dtype: float64
y-intercept :  0    22.618128
Name: 1, dtype: float64
test_num :  826
slope :  0    0.930127
Name: 0, dtype: float64
y-intercept :  0    22.619608
Name: 1, dtype: float64
test_num :  827
slope :  0    0.930009
Name: 0, dtype: float64
y-intercept :  0    22.621082
Name: 1, dtype: float64
test_num :  828
slope :  0    0.929892
Name: 0, dtype: float64
y-intercept :  0    22.622548
Name: 1, dtype: float64
test_num :  829
slope :  0    0.929775
Name: 0, dtype: float64
y-intercept :  0    22.624009
Name: 1, dtype: float64
test_num :  830
slope :  0    0.929659
Name: 0, dtype: float64
y-intercept :  0    22.625462
Name: 1, dtype: float64
test_num :  831
slope :  0    0.929543
Name: 0, dtype: float64
y-intercept :  0    22.62691
Name: 1, dtype: float64
test_num :  832
slope :  0    0.929427
Name: 0, dtype: float64
y-intercept :  0    22.62835
Name: 1, dtype: float64
test_num :  833
slope :  0    0.929312
Name: 0, dtype: float64
y-intercept :  0    22.629785
Name: 1, dtype: float64
test_num :  834
slope :  0    0.929198
Name: 0, dtype: float64
y-intercept :  0    22.631212
Name: 1, dtype: float64
test_num :  835
slope :  0    0.929084
Name: 0, dtype: float64
y-intercept :  0    22.632634
Name: 1, dtype: float64
test_num :  836
slope :  0    0.928971
Name: 0, dtype: float64
y-intercept :  0    22.634049
Name: 1, dtype: float64
test_num :  837
slope :  0    0.928858
Name: 0, dtype: float64
y-intercept :  0    22.635457
Name: 1, dtype: float64

test_num :  838
slope :  0    0.928746
Name: 0, dtype: float64
y-intercept :  0    22.636859
Name: 1, dtype: float64
test_num :  839
slope :  0    0.928634
Name: 0, dtype: float64
y-intercept :  0    22.638255
Name: 1, dtype: float64
test_num :  840
slope :  0    0.928523
Name: 0, dtype: float64
y-intercept :  0    22.639645
Name: 1, dtype: float64
test_num :  841
slope :  0    0.928412
Name: 0, dtype: float64
y-intercept :  0    22.641029
Name: 1, dtype: float64
test_num :  842
slope :  0    0.928302
Name: 0, dtype: float64
y-intercept :  0    22.642406
Name: 1, dtype: float64
test_num :  843
slope :  0    0.928192
Name: 0, dtype: float64
y-intercept :  0    22.643777
Name: 1, dtype: float64
test_num :  844
slope :  0    0.928083
Name: 0, dtype: float64
y-intercept :  0    22.645142
Name: 1, dtype: float64
test_num :  845
slope :  0    0.927974
Name: 0, dtype: float64
y-intercept :  0    22.646501
Name: 1, dtype: float64
test_num :  846
slope :  0    0.927866
Name: 0, dtype: float64
y-intercept :  0    22.647853
Name: 1, dtype: float64
test_num :  847
slope :  0    0.927758
Name: 0, dtype: float64
y-intercept :  0    22.6492
Name: 1, dtype: float64
test_num :  848
slope :  0    0.92765
Name: 0, dtype: float64
y-intercept :  0    22.65054
Name: 1, dtype: float64
test_num :  849
slope :  0    0.927544
Name: 0, dtype: float64
y-intercept :  0    22.651875
Name: 1, dtype: float64
test_num :  850
slope :  0    0.927437
Name: 0, dtype: float64
y-intercept :  0    22.653203
Name: 1, dtype: float64
test_num :  851
slope :  0    0.927331
Name: 0, dtype: float64
y-intercept :  0    22.654526
Name: 1, dtype: float64
test_num :  852
slope :  0    0.927226
Name: 0, dtype: float64
y-intercept :  0    22.655842
Name: 1, dtype: float64
test_num :  853
slope :  0    0.927121
Name: 0, dtype: float64
y-intercept :  0    22.657153
Name: 1, dtype: float64
test_num :  854
slope :  0    0.927016
Name: 0, dtype: float64
y-intercept :  0    22.658458
Name: 1, dtype: float64
test_num :  855
slope :  0    0.926912
Name: 0, dtype: float64
y-intercept :  0    22.659757
Name: 1, dtype: float64
test_num :  856
slope :  0    0.926809
Name: 0, dtype: float64
y-intercept :  0    22.66105
Name: 1, dtype: float64
test_num :  857
slope :  0    0.926706
Name: 0, dtype: float64
y-intercept :  0    22.662337
Name: 1, dtype: float64
test_num :  858
slope :  0    0.926603
Name: 0, dtype: float64
y-intercept :  0    22.663619
Name: 1, dtype: float64
test_num :  859
slope :  0    0.926501
Name: 0, dtype: float64
y-intercept :  0    22.664894
Name: 1, dtype: float64
test_num :  860
slope :  0    0.926399
Name: 0, dtype: float64
y-intercept :  0    22.666164
Name: 1, dtype: float64
test_num :  861
slope :  0    0.926298
Name: 0, dtype: float64
y-intercept :  0    22.667429
Name: 1, dtype: float64
test_num :  862
slope :  0    0.926197
Name: 0, dtype: float64
y-intercept :  0    22.668687
Name: 1, dtype: float64
test_num :  863
slope :  0    0.926097
Name: 0, dtype: float64
y-intercept :  0    22.66994
Name: 1, dtype: float64
test_num :  864
slope :  0    0.925997
Name: 0, dtype: float64
y-intercept :  0    22.671188
Name: 1, dtype: float64
test_num :  865
slope :  0    0.925898
Name: 0, dtype: float64
y-intercept :  0    22.672429
Name: 1, dtype: float64
test_num :  866
slope :  0    0.925799
Name: 0, dtype: float64
y-intercept :  0    22.673666
Name: 1, dtype: float64
test_num :  867
slope :  0    0.9257
Name: 0, dtype: float64
y-intercept :  0    22.674896
Name: 1, dtype: float64
test_num :  868
slope :  0    0.925602
Name: 0, dtype: float64
y-intercept :  0    22.676121
Name: 1, dtype: float64
test_num :  869
slope :  0    0.925504
Name: 0, dtype: float64
y-intercept :  0    22.677341
Name: 1, dtype: float64
test_num :  870
slope :  0    0.925407
Name: 0, dtype: float64
y-intercept :  0    22.678555
Name: 1, dtype: float64
test_num :  871
slope :  0    0.92531
Name: 0, dtype: float64
y-intercept :  0    22.679764
Name: 1, dtype: float64
test_num :  872
slope :  0    0.925214
Name: 0, dtype: float64
y-intercept :  0    22.680967
Name: 1, dtype: float64
test_num :  873
slope :  0    0.925118
Name: 0, dtype: float64
y-intercept :  0    22.682165
Name: 1, dtype: float64
test_num :  874
slope :  0    0.925022
Name: 0, dtype: float64
y-intercept :  0    22.683357
Name: 1, dtype: float64
test_num :  875
slope :  0    0.924927
Name: 0, dtype: float64
y-intercept :  0    22.684544
Name: 1, dtype: float64
test_num :  876
slope :  0    0.924833
Name: 0, dtype: float64
y-intercept :  0    22.685726
Name: 1, dtype: float64
test_num :  877
slope :  0    0.924739
Name: 0, dtype: float64
y-intercept :  0    22.686902
Name: 1, dtype: float64
test_num :  878
slope :  0    0.924645
Name: 0, dtype: float64
y-intercept :  0    22.688073
Name: 1, dtype: float64
test_num :  879
slope :  0    0.924551
Name: 0, dtype: float64
y-intercept :  0    22.689239
Name: 1, dtype: float64
test_num :  880
slope :  0    0.924458
Name: 0, dtype: float64
y-intercept :  0    22.6904
Name: 1, dtype: float64
test_num :  881
slope :  0    0.924366
Name: 0, dtype: float64
y-intercept :  0    22.691555
Name: 1, dtype: float64
test_num :  882
slope :  0    0.924274
Name: 0, dtype: float64
y-intercept :  0    22.692705
Name: 1, dtype: float64
test_num :  883
slope :  0    0.924182
Name: 0, dtype: float64
y-intercept :  0    22.69385
Name: 1, dtype: float64
test_num :  884
slope :  0    0.924091
Name: 0, dtype: float64
y-intercept :  0    22.69499
Name: 1, dtype: float64
test_num :  885
slope :  0    0.924
Name: 0, dtype: float64
y-intercept :  0    22.696125
Name: 1, dtype: float64
test_num :  886
slope :  0    0.92391
Name: 0, dtype: float64
y-intercept :  0    22.697255
Name: 1, dtype: float64
test_num :  887
slope :  0    0.923819
Name: 0, dtype: float64
y-intercept :  0    22.698379
Name: 1, dtype: float64
test_num :  888
slope :  0    0.92373
Name: 0, dtype: float64
y-intercept :  0    22.699499
Name: 1, dtype: float64
test_num :  889
slope :  0    0.923641
Name: 0, dtype: float64
y-intercept :  0    22.700613
Name: 1, dtype: float64
test_num :  890
slope :  0    0.923552
Name: 0, dtype: float64
y-intercept :  0    22.701723
Name: 1, dtype: float64
test_num :  891
slope :  0    0.923463
Name: 0, dtype: float64
y-intercept :  0    22.702828
Name: 1, dtype: float64
test_num :  892
slope :  0    0.923375
Name: 0, dtype: float64
y-intercept :  0    22.703927
Name: 1, dtype: float64
test_num :  893
slope :  0    0.923288
Name: 0, dtype: float64
y-intercept :  0    22.705022
Name: 1, dtype: float64
test_num :  894
slope :  0    0.9232
Name: 0, dtype: float64
y-intercept :  0    22.706111
Name: 1, dtype: float64
test_num :  895
slope :  0    0.923113
Name: 0, dtype: float64
y-intercept :  0    22.707196
Name: 1, dtype: float64
test_num :  896
slope :  0    0.923027
Name: 0, dtype: float64
y-intercept :  0    22.708276
Name: 1, dtype: float64
test_num :  897
slope :  0    0.922941
Name: 0, dtype: float64
y-intercept :  0    22.709351
Name: 1, dtype: float64
test_num :  898
slope :  0    0.922855
Name: 0, dtype: float64
y-intercept :  0    22.710422
Name: 1, dtype: float64
test_num :  899
slope :  0    0.92277
Name: 0, dtype: float64
y-intercept :  0    22.711487
Name: 1, dtype: float64
test_num :  900
slope :  0    0.922685
Name: 0, dtype: float64
y-intercept :  0    22.712548
Name: 1, dtype: float64
test_num :  901
slope :  0    0.9226
Name: 0, dtype: float64
y-intercept :  0    22.713604
Name: 1, dtype: float64
test_num :  902
slope :  0    0.922516
Name: 0, dtype: float64
y-intercept :  0    22.714655
Name: 1, dtype: float64
test_num :  903
slope :  0    0.922432
Name: 0, dtype: float64
y-intercept :  0    22.715701
Name: 1, dtype: float64
test_num :  904
slope :  0    0.922349
Name: 0, dtype: float64
y-intercept :  0    22.716743
Name: 1, dtype: float64
test_num :  905
slope :  0    0.922266
Name: 0, dtype: float64
y-intercept :  0    22.71778
Name: 1, dtype: float64
test_num :  906
slope :  0    0.922183
Name: 0, dtype: float64
y-intercept :  0    22.718812
Name: 1, dtype: float64
test_num :  907
slope :  0    0.922101
Name: 0, dtype: float64
y-intercept :  0    22.71984
Name: 1, dtype: float64
test_num :  908
slope :  0    0.922019
Name: 0, dtype: float64
y-intercept :  0    22.720863
Name: 1, dtype: float64
test_num :  909
slope :  0    0.921937
Name: 0, dtype: float64
y-intercept :  0    22.721882
Name: 1, dtype: float64
test_num :  910
slope :  0    0.921856
Name: 0, dtype: float64
y-intercept :  0    22.722896
Name: 1, dtype: float64
test_num :  911
slope :  0    0.921775
Name: 0, dtype: float64
y-intercept :  0    22.723905
Name: 1, dtype: float64
test_num :  912
slope :  0    0.921695
Name: 0, dtype: float64
y-intercept :  0    22.72491
Name: 1, dtype: float64
test_num :  913
slope :  0    0.921615
Name: 0, dtype: float64
y-intercept :  0    22.72591
Name: 1, dtype: float64
test_num :  914
slope :  0    0.921535
Name: 0, dtype: float64
y-intercept :  0    22.726906
Name: 1, dtype: float64
test_num :  915
slope :  0    0.921456
Name: 0, dtype: float64
y-intercept :  0    22.727898
Name: 1, dtype: float64
test_num :  916
slope :  0    0.921377
Name: 0, dtype: float64
y-intercept :  0    22.728884
Name: 1, dtype: float64
test_num :  917
slope :  0    0.921298
Name: 0, dtype: float64
y-intercept :  0    22.729867
Name: 1, dtype: float64
test_num :  918
slope :  0    0.92122
Name: 0, dtype: float64
y-intercept :  0    22.730845
Name: 1, dtype: float64
test_num :  919
slope :  0    0.921142
Name: 0, dtype: float64
y-intercept :  0    22.731819
Name: 1, dtype: float64
test_num :  920
slope :  0    0.921064
Name: 0, dtype: float64
y-intercept :  0    22.732788
Name: 1, dtype: float64
test_num :  921
slope :  0    0.920987
Name: 0, dtype: float64
y-intercept :  0    22.733753
Name: 1, dtype: float64
test_num :  922
slope :  0    0.92091
Name: 0, dtype: float64
y-intercept :  0    22.734714
Name: 1, dtype: float64
test_num :  923
slope :  0    0.920833
Name: 0, dtype: float64
y-intercept :  0    22.73567
Name: 1, dtype: float64
test_num :  924
slope :  0    0.920757
Name: 0, dtype: float64
y-intercept :  0    22.736622
Name: 1, dtype: float64
test_num :  925
slope :  0    0.920681
Name: 0, dtype: float64
y-intercept :  0    22.73757
Name: 1, dtype: float64
test_num :  926
slope :  0    0.920606
Name: 0, dtype: float64
y-intercept :  0    22.738513
Name: 1, dtype: float64
test_num :  927
slope :  0    0.92053
Name: 0, dtype: float64
y-intercept :  0    22.739452
Name: 1, dtype: float64
test_num :  928
slope :  0    0.920456
Name: 0, dtype: float64
y-intercept :  0    22.740387
Name: 1, dtype: float64
test_num :  929
slope :  0    0.920381
Name: 0, dtype: float64
y-intercept :  0    22.741318
Name: 1, dtype: float64
test_num :  930
slope :  0    0.920307
Name: 0, dtype: float64
y-intercept :  0    22.742245
Name: 1, dtype: float64
test_num :  931
slope :  0    0.920233
Name: 0, dtype: float64
y-intercept :  0    22.743167
Name: 1, dtype: float64
test_num :  932
slope :  0    0.920159
Name: 0, dtype: float64
y-intercept :  0    22.744086
Name: 1, dtype: float64
test_num :  933
slope :  0    0.920086
Name: 0, dtype: float64
y-intercept :  0    22.745
Name: 1, dtype: float64
test_num :  934
slope :  0    0.920013
Name: 0, dtype: float64
y-intercept :  0    22.74591
Name: 1, dtype: float64
test_num :  935
slope :  0    0.919941
Name: 0, dtype: float64
y-intercept :  0    22.746816
Name: 1, dtype: float64
test_num :  936
slope :  0    0.919868
Name: 0, dtype: float64
y-intercept :  0    22.747718
Name: 1, dtype: float64
test_num :  937
slope :  0    0.919797
Name: 0, dtype: float64
y-intercept :  0    22.748616
Name: 1, dtype: float64
test_num :  938
slope :  0    0.919725
Name: 0, dtype: float64
y-intercept :  0    22.74951
Name: 1, dtype: float64
test_num :  939
slope :  0    0.919654
Name: 0, dtype: float64
y-intercept :  0    22.750399
Name: 1, dtype: float64
test_num :  940
slope :  0    0.919583
Name: 0, dtype: float64
y-intercept :  0    22.751285
Name: 1, dtype: float64
test_num :  941
slope :  0    0.919512
Name: 0, dtype: float64
y-intercept :  0    22.752167
Name: 1, dtype: float64
test_num :  942
slope :  0    0.919442
Name: 0, dtype: float64
y-intercept :  0    22.753045
Name: 1, dtype: float64
test_num :  943
slope :  0    0.919372
Name: 0, dtype: float64
y-intercept :  0    22.753919
Name: 1, dtype: float64
test_num :  944
slope :  0    0.919302
Name: 0, dtype: float64
y-intercept :  0    22.754789
Name: 1, dtype: float64
test_num :  945
slope :  0    0.919233
Name: 0, dtype: float64
y-intercept :  0    22.755655
Name: 1, dtype: float64
test_num :  946
slope :  0    0.919164
Name: 0, dtype: float64
y-intercept :  0    22.756517
Name: 1, dtype: float64
test_num :  947
slope :  0    0.919095
Name: 0, dtype: float64
y-intercept :  0    22.757376
Name: 1, dtype: float64
test_num :  948
slope :  0    0.919027
Name: 0, dtype: float64
y-intercept :  0    22.75823
Name: 1, dtype: float64
test_num :  949
slope :  0    0.918959
Name: 0, dtype: float64
y-intercept :  0    22.759081
Name: 1, dtype: float64
test_num :  950
slope :  0    0.918891
Name: 0, dtype: float64
y-intercept :  0    22.759927
Name: 1, dtype: float64
test_num :  951
slope :  0    0.918823
Name: 0, dtype: float64
y-intercept :  0    22.76077
Name: 1, dtype: float64
test_num :  952
slope :  0    0.918756
Name: 0, dtype: float64
y-intercept :  0    22.76161
Name: 1, dtype: float64
test_num :  953
slope :  0    0.918689
Name: 0, dtype: float64
y-intercept :  0    22.762445
Name: 1, dtype: float64
test_num :  954
slope :  0    0.918623
Name: 0, dtype: float64
y-intercept :  0    22.763277
Name: 1, dtype: float64
test_num :  955
slope :  0    0.918556
Name: 0, dtype: float64
y-intercept :  0    22.764105
Name: 1, dtype: float64
test_num :  956
slope :  0    0.91849
Name: 0, dtype: float64
y-intercept :  0    22.764929
Name: 1, dtype: float64
test_num :  957
slope :  0    0.918425
Name: 0, dtype: float64
y-intercept :  0    22.76575
Name: 1, dtype: float64
test_num :  958
slope :  0    0.918359
Name: 0, dtype: float64
y-intercept :  0    22.766566
Name: 1, dtype: float64
test_num :  959
slope :  0    0.918294
Name: 0, dtype: float64
y-intercept :  0    22.76738
Name: 1, dtype: float64
test_num :  960
slope :  0    0.918229
Name: 0, dtype: float64
y-intercept :  0    22.768189
Name: 1, dtype: float64
test_num :  961
slope :  0    0.918165
Name: 0, dtype: float64
y-intercept :  0    22.768995
Name: 1, dtype: float64
test_num :  962
slope :  0    0.9181
Name: 0, dtype: float64
y-intercept :  0    22.769797
Name: 1, dtype: float64
test_num :  963
slope :  0    0.918036
Name: 0, dtype: float64
y-intercept :  0    22.770596
Name: 1, dtype: float64
test_num :  964
slope :  0    0.917973
Name: 0, dtype: float64
y-intercept :  0    22.771391
Name: 1, dtype: float64
test_num :  965
slope :  0    0.917909
Name: 0, dtype: float64
y-intercept :  0    22.772183
Name: 1, dtype: float64
test_num :  966
slope :  0    0.917846
Name: 0, dtype: float64
y-intercept :  0    22.772971
Name: 1, dtype: float64
test_num :  967
slope :  0    0.917783
Name: 0, dtype: float64
y-intercept :  0    22.773755
Name: 1, dtype: float64
test_num :  968
slope :  0    0.917721
Name: 0, dtype: float64
y-intercept :  0    22.774536
Name: 1, dtype: float64
test_num :  969
slope :  0    0.917659
Name: 0, dtype: float64
y-intercept :  0    22.775313
Name: 1, dtype: float64
test_num :  970
slope :  0    0.917597
Name: 0, dtype: float64
y-intercept :  0    22.776087
Name: 1, dtype: float64
test_num :  971
slope :  0    0.917535
Name: 0, dtype: float64
y-intercept :  0    22.776858
Name: 1, dtype: float64
test_num :  972
slope :  0    0.917474
Name: 0, dtype: float64
y-intercept :  0    22.777625
Name: 1, dtype: float64
test_num :  973
slope :  0    0.917412
Name: 0, dtype: float64
y-intercept :  0    22.778388
Name: 1, dtype: float64
test_num :  974
slope :  0    0.917352
Name: 0, dtype: float64
y-intercept :  0    22.779148
Name: 1, dtype: float64
test_num :  975
slope :  0    0.917291
Name: 0, dtype: float64
y-intercept :  0    22.779905
Name: 1, dtype: float64
test_num :  976
slope :  0    0.917231
Name: 0, dtype: float64
y-intercept :  0    22.780658
Name: 1, dtype: float64
test_num :  977
slope :  0    0.917171
Name: 0, dtype: float64
y-intercept :  0    22.781408
Name: 1, dtype: float64
test_num :  978
slope :  0    0.917111
Name: 0, dtype: float64
y-intercept :  0    22.782154
Name: 1, dtype: float64
test_num :  979
slope :  0    0.917051
Name: 0, dtype: float64
y-intercept :  0    22.782898
Name: 1, dtype: float64
test_num :  980
slope :  0    0.916992
Name: 0, dtype: float64
y-intercept :  0    22.783637
Name: 1, dtype: float64
test_num :  981
slope :  0    0.916933
Name: 0, dtype: float64
y-intercept :  0    22.784374
Name: 1, dtype: float64
test_num :  982
slope :  0    0.916874
Name: 0, dtype: float64
y-intercept :  0    22.785107
Name: 1, dtype: float64
test_num :  983
slope :  0    0.916816
Name: 0, dtype: float64
y-intercept :  0    22.785837
Name: 1, dtype: float64
test_num :  984
slope :  0    0.916758
Name: 0, dtype: float64
y-intercept :  0    22.786563
Name: 1, dtype: float64
test_num :  985
slope :  0    0.9167
Name: 0, dtype: float64
y-intercept :  0    22.787287
Name: 1, dtype: float64
test_num :  986
slope :  0    0.916642
Name: 0, dtype: float64
y-intercept :  0    22.788007
Name: 1, dtype: float64
test_num :  987
slope :  0    0.916585
Name: 0, dtype: float64
y-intercept :  0    22.788724
Name: 1, dtype: float64
test_num :  988
slope :  0    0.916528
Name: 0, dtype: float64
y-intercept :  0    22.789437
Name: 1, dtype: float64
test_num :  989
slope :  0    0.916471
Name: 0, dtype: float64
y-intercept :  0    22.790148
Name: 1, dtype: float64
test_num :  990
slope :  0    0.916414
Name: 0, dtype: float64
y-intercept :  0    22.790855
Name: 1, dtype: float64
test_num :  991
slope :  0    0.916358
Name: 0, dtype: float64
y-intercept :  0    22.791559
Name: 1, dtype: float64
test_num :  992
slope :  0    0.916302
Name: 0, dtype: float64
y-intercept :  0    22.79226
Name: 1, dtype: float64
test_num :  993
slope :  0    0.916246
Name: 0, dtype: float64
y-intercept :  0    22.792958
Name: 1, dtype: float64
test_num :  994
slope :  0    0.91619
Name: 0, dtype: float64
y-intercept :  0    22.793652
Name: 1, dtype: float64
test_num :  995
slope :  0    0.916135
Name: 0, dtype: float64
y-intercept :  0    22.794344
Name: 1, dtype: float64
test_num :  996
slope :  0    0.91608
Name: 0, dtype: float64
y-intercept :  0    22.795032
Name: 1, dtype: float64
test_num :  997
slope :  0    0.916025
Name: 0, dtype: float64
y-intercept :  0    22.795717
Name: 1, dtype: float64
test_num :  998
slope :  0    0.91597
Name: 0, dtype: float64
y-intercept :  0    22.7964
Name: 1, dtype: float64
test_num :  999
slope :  0    0.915916
Name: 0, dtype: float64
y-intercept :  0    22.797079
Name: 1, dtype: float64

In [92]:
print("slope : ",W.iloc[0])
print("y-intercept : ",W.iloc[1])

slope :  0    0.915916
Name: 0, dtype: float64
y-intercept :  0    22.797079
Name: 1, dtype: float64